// Branch Level "Ember Forge" (id: b1) — see levels.js's
// TRUE_BRANCH_LEVELS and docs/gameplay.md's "Ten themed branch levels".
// Reachable only from its own Level Map node, never part of the
// sequential 1-100 path — see game.js's startBranchLevelFromOverlay()/
// completeBranchLevel(). Generated by .claude/gen-branch-levels.js;
// re-run audit-gaps.js/audit-checkpoints.js after regenerating.

window.levelText = "Ember Forge";
window.levelTheme = "ember";
window.levelBranchId = "b1";

window.platforms = [
  { x: 50, y: 380, width: 260, height: 20 },
  { x: 710, y: 303, width: 116, height: 25, bounce: true, bounceStrength: -22 },
  { x: 1006, y: 231, width: 185, height: 20 },
  { x: 1396, y: 198, width: 150, height: 29, bounce: true, bounceStrength: -21 },
  { x: 1974, y: 178, width: 206, height: 31, moveAxis: "y", moveRange: 103, moveSpeed: 0.058, movePhase: 0.94 },
  { x: 2339, y: 178, width: 347, height: 23 },
  { x: 2918, y: 219, width: 150, height: 24 },
  { x: 3304, y: 273, width: 135, height: 27, melt: true, meltDelay: 18 },
  { x: 3681, y: 355, width: 64, height: 18, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 3904, y: 355, width: 417, height: 20 },
  { x: 4563, y: 432, width: 241, height: 16, moveAxis: "x", moveRange: 120, moveSpeed: 0.058, movePhase: 1.98 },
  { x: 5046, y: 516, width: 127, height: 30, bounce: true, bounceStrength: -19 },
  { x: 5409, y: 567, width: 74, height: 18, moveAxis: "y", moveRange: 138, moveSpeed: 0.063, movePhase: 1.33 },
  { x: 5715, y: 608, width: 149, height: 16 },
  { x: 6023, y: 608, width: 276, height: 29 },
  { x: 6721, y: 579, width: 103, height: 19, melt: true, meltDelay: 18 },
  { x: 7014, y: 521, width: 230, height: 19, moveAxis: "x", moveRange: 86, moveSpeed: 0.062, movePhase: 1.72 },
  { x: 7421, y: 438, width: 129, height: 29 },
  { x: 7712, y: 337, width: 241, height: 14, conveyor: true, conveyorSpeed: -2.2 },
  { x: 8112, y: 337, width: 392, height: 27 },
  { x: 8671, y: 243, width: 155, height: 30, bounce: true, bounceStrength: -19 },
  { x: 9235, y: 177, width: 62, height: 18 },
  { x: 9701, y: 110, width: 86, height: 19 },
  { x: 10209, y: 85, width: 193, height: 15, moveAxis: "y", moveRange: 131, moveSpeed: 0.041, movePhase: 1.02 },
  { x: 10834, y: 80, width: 55, height: 24, melt: true, meltDelay: 18 },
  { x: 11048, y: 80, width: 347, height: 31 },
  { x: 11627, y: 126, width: 138, height: 17, melt: true, meltDelay: 18 },
  { x: 12007, y: 203, width: 79, height: 20, melt: true, meltDelay: 18 },
  { x: 12328, y: 294, width: 181, height: 17 },
  { x: 12668, y: 294, width: 368, height: 30 },
  { x: 13278, y: 379, width: 217, height: 27 },
  { x: 13737, y: 464, width: 77, height: 23, melt: true, meltDelay: 18 },
  { x: 14050, y: 519, width: 204, height: 31, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 14481, y: 556, width: 99, height: 22 },
  { x: 14798, y: 563, width: 194, height: 23, conveyor: true, conveyorSpeed: 2.07 },
  { x: 15151, y: 563, width: 319, height: 23 },
  { x: 15660, y: 506, width: 50, height: 26, melt: true, meltDelay: 18 },
  { x: 16114, y: 435, width: 116, height: 30, bounce: true, bounceStrength: -22 },
  { x: 16397, y: 336, width: 154, height: 25, melt: true, meltDelay: 18 },
  { x: 16710, y: 336, width: 294, height: 17 },
  { x: 17184, y: 263, width: 225, height: 19 },
  { x: 17585, y: 269, width: 462, height: 20 },
];

window.deadlyPlatforms = [
  { x: 4656, y: 488, width: 173, height: 20, moveAxis: "y", moveRange: 91, moveSpeed: 0.067, movePhase: 2.46 },
  { x: 6935, y: 476, width: 191, height: 17, moveAxis: "y", moveRange: 78, moveSpeed: 0.06, movePhase: 0.09 },
  { x: 3100, y: 227, width: 93, height: 20 },
  { x: 7577, y: 446, width: 82, height: 20 },
  { x: 13523, y: 373, width: 164, height: 20 },
  { x: 14616, y: 555, width: 60, height: 20 },
];

window.spikes = [
  { x: 2961, y: 219, size: 27 },
  { x: 9718, y: 110, size: 21 },
  { x: 9739, y: 110, size: 29 },
  { x: 14516, y: 556, size: 29 },
  { x: 17213, y: 263, size: 15 },
];

window.checkpoints = [
  { x: 150, y: 350, reached: false },
  { x: 2513, y: 148, reached: false },
  { x: 4113, y: 325, reached: false },
  { x: 6161, y: 578, reached: false },
  { x: 8308, y: 307, reached: false },
  { x: 11222, y: 50, reached: false },
  { x: 12852, y: 264, reached: false },
  { x: 15311, y: 533, reached: false },
  { x: 16857, y: 306, reached: false },
  { x: 17816, y: 239, reached: false }, // Final
];

window.lasers = [
  { x: 1623, y: 124, length: 216, width: 4, baseAngle: 0.06, sweepAngle: 1.15, period: 152, blinkPeriod: 0, onRatio: 0.5 },
  { x: 3505, y: 169, length: 233, width: 4, baseAngle: 0.77, sweepAngle: 0, period: 152, blinkPeriod: 103, onRatio: 0.5 },
  { x: 4864, y: 335, length: 190, width: 4, baseAngle: 4.89, sweepAngle: 0, period: 152, blinkPeriod: 103, onRatio: 0.5 },
  { x: 5237, y: 416, length: 119, width: 4, baseAngle: 2.44, sweepAngle: 0, period: 152, blinkPeriod: 103, onRatio: 0.5 },
  { x: 5920, y: 547, length: 169, width: 4, baseAngle: 0.22, sweepAngle: 0.68, period: 152, blinkPeriod: 0, onRatio: 0.5 },
  { x: 7332, y: 434, length: 205, width: 4, baseAngle: 1.19, sweepAngle: 0.82, period: 152, blinkPeriod: 0, onRatio: 0.5 },
  { x: 7643, y: 380, length: 211, width: 4, baseAngle: 0.46, sweepAngle: 0.84, period: 152, blinkPeriod: 0, onRatio: 0.5 },
  { x: 8045, y: 233, length: 196, width: 4, baseAngle: 4.03, sweepAngle: 0.63, period: 152, blinkPeriod: 0, onRatio: 0.5 },
  { x: 9875, y: 1, length: 250, width: 4, baseAngle: 5.33, sweepAngle: 0.63, period: 152, blinkPeriod: 0, onRatio: 0.5 },
  { x: 10471, y: 38, length: 131, width: 4, baseAngle: 3.83, sweepAngle: 0.89, period: 152, blinkPeriod: 0, onRatio: 0.5 },
  { x: 11855, y: 72, length: 252, width: 4, baseAngle: 0.63, sweepAngle: 0.76, period: 152, blinkPeriod: 0, onRatio: 0.5 },
  { x: 13870, y: 365, length: 247, width: 4, baseAngle: 2.96, sweepAngle: 0, period: 152, blinkPeriod: 103, onRatio: 0.5 },
  { x: 14660, y: 483, length: 185, width: 4, baseAngle: 2.63, sweepAngle: 0, period: 152, blinkPeriod: 103, onRatio: 0.5 },
  { x: 15068, y: 476, length: 147, width: 4, baseAngle: 3.07, sweepAngle: 0, period: 152, blinkPeriod: 103, onRatio: 0.5 },
  { x: 15801, y: 455, length: 243, width: 4, baseAngle: 5.5, sweepAngle: 0.85, period: 152, blinkPeriod: 0, onRatio: 0.5 },
];

window.fallers = [
  { x: 882, y: 183, size: 45, triggerX: 695 },
  { x: 2278, y: 54, size: 47, triggerX: 2105 },
  { x: 3139, y: 70, size: 37, triggerX: 3003 },
  { x: 3831, y: 219, size: 24, triggerX: 3617 },
  { x: 9372, y: 89, size: 31, triggerX: 9196 },
  { x: 10987, y: -33, size: 55, triggerX: 10834 },
  { x: 12148, y: 121, size: 41, triggerX: 11983 },
  { x: 16631, y: 207, size: 32, triggerX: 16414 },
  { x: 17489, y: 141, size: 49, triggerX: 17322 },
];
