// Branch Level "Abyssal Trench" (id: b6) — see levels.js's
// TRUE_BRANCH_LEVELS and docs/gameplay.md's "Ten themed branch levels".
// Reachable only from its own Level Map node, never part of the
// sequential 1-100 path — see game.js's startBranchLevelFromOverlay()/
// completeBranchLevel(). Generated by .claude/gen-branch-levels.js;
// re-run audit-gaps.js/audit-checkpoints.js after regenerating.

window.levelText = "Abyssal Trench";
window.levelTheme = "abyssal";
window.levelBranchId = "b6";

window.platforms = [
  { x: 50, y: 380, width: 260, height: 20 },
  { x: 504, y: 323, width: 243, height: 29 },
  { x: 1156, y: 245, width: 137, height: 18 },
  { x: 1686, y: 133, width: 196, height: 31, melt: true, meltDelay: 18 },
  { x: 2057, y: 43, width: 81, height: 30, bounce: true, bounceStrength: -20 },
  { x: 2297, y: 43, width: 355, height: 17 },
  { x: 3070, y: -18, width: 249, height: 24 },
  { x: 3522, y: -54, width: 85, height: 27 },
  { x: 3820, y: -66, width: 219, height: 31 },
  { x: 4261, y: -61, width: 140, height: 30, conveyor: true, conveyorSpeed: -1.18 },
  { x: 4642, y: -7, width: 149, height: 15, conveyor: true, conveyorSpeed: 2.19 },
  { x: 4950, y: -7, width: 366, height: 14 },
  { x: 5563, y: 73, width: 173, height: 26, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 5983, y: 180, width: 151, height: 14 },
  { x: 6381, y: 268, width: 153, height: 15, moveAxis: "x", moveRange: 112, moveSpeed: 0.068, movePhase: 4.29 },
  { x: 6781, y: 368, width: 90, height: 23, bounce: true, bounceStrength: -20 },
  { x: 7030, y: 368, width: 363, height: 23 },
  { x: 7634, y: 426, width: 190, height: 23, conveyor: true, conveyorSpeed: -1.96 },
  { x: 8046, y: 427, width: 188, height: 24, conveyor: true, conveyorSpeed: -1.32 },
  { x: 8665, y: 400, width: 229, height: 20 },
  { x: 9053, y: 400, width: 306, height: 16 },
  { x: 9768, y: 314, width: 57, height: 29 },
  { x: 9987, y: 204, width: 162, height: 30 },
  { x: 10542, y: 91, width: 107, height: 29 },
  { x: 10820, y: -3, width: 248, height: 18 },
  { x: 11227, y: -3, width: 401, height: 15 },
  { x: 11822, y: -61, width: 221, height: 24, moveAxis: "y", moveRange: 105, moveSpeed: 0.047, movePhase: 4.3 },
  { x: 12246, y: -96, width: 194, height: 28, bounce: true, bounceStrength: -21 },
  { x: 12881, y: -100, width: 167, height: 27, conveyor: true, conveyorSpeed: -2.1 },
  { x: 13286, y: -54, width: 194, height: 27, moveAxis: "y", moveRange: 113, moveSpeed: 0.06, movePhase: 3.02 },
  { x: 13639, y: -54, width: 377, height: 31 },
  { x: 14263, y: 39, width: 129, height: 20, moveAxis: "x", moveRange: 138, moveSpeed: 0.066, movePhase: 4.44 },
  { x: 14639, y: 132, width: 74, height: 26, moveAxis: "y", moveRange: 154, moveSpeed: 0.064, movePhase: 3.71 },
  { x: 14960, y: 240, width: 104, height: 20, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 15223, y: 240, width: 299, height: 24 },
  { x: 15769, y: 319, width: 101, height: 27 },
  { x: 16117, y: 391, width: 172, height: 22 },
  { x: 16521, y: 424, width: 111, height: 26 },
  { x: 16854, y: 430, width: 92, height: 26 },
  { x: 17377, y: 399, width: 212, height: 28, melt: true, meltDelay: 18 },
  { x: 17748, y: 399, width: 268, height: 21 },
  { x: 18415, y: 301, width: 162, height: 19, bounce: true, bounceStrength: -17 },
  { x: 18976, y: 202, width: 61, height: 23 },
  { x: 19250, y: 211, width: 417, height: 20 },
  { x: 2802, y: 15, width: 108, height: 16, gated: true, gateId: "b6_g0" },
];

window.deadlyPlatforms = [
  { x: 13337, y: -10, width: 122, height: 20, moveAxis: "x", moveRange: 115, moveSpeed: 0.066, movePhase: 3.48 },
  { x: 4062, y: -74, width: 165, height: 20 },
  { x: 8932, y: 407, width: 180, height: 20 },
  { x: 10673, y: 87, width: 72, height: 20 },
  { x: 15904, y: 311, width: 74, height: 20 },
  { x: 16972, y: 435, width: 60, height: 20 },
];

window.spikes = [
  { x: 3122, y: -18, size: 19 },
  { x: 3141, y: -18, size: 13 },
  { x: 3868, y: -66, size: 22 },
  { x: 3890, y: -66, size: 40 },
  { x: 3930, y: -66, size: 28 },
  { x: 6003, y: 180, size: 42 },
  { x: 8734, y: 400, size: 59 },
  { x: 10560, y: 91, size: 12 },
  { x: 10572, y: 91, size: 51 },
  { x: 10623, y: 91, size: 17 },
  { x: 10911, y: -3, size: 23 },
  { x: 10934, y: -3, size: 52 },
  { x: 15799, y: 319, size: 41 },
];

window.checkpoints = [
  { x: 150, y: 350, reached: false },
  { x: 2475, y: 13, reached: false },
  { x: 5133, y: -37, reached: false },
  { x: 7212, y: 338, reached: false },
  { x: 9206, y: 370, reached: false },
  { x: 11428, y: -33, reached: false },
  { x: 13828, y: -84, reached: false },
  { x: 15373, y: 210, reached: false },
  { x: 17882, y: 369, reached: false },
  { x: 19459, y: 181, reached: false }, // Final
];

window.forceZones = [
  { x: 4960, y: -97, width: 346, height: 90, axis: "x", force: -0.203 },
  { x: 7040, y: 278, width: 343, height: 90, axis: "x", force: -0.135 },
  { x: 9059, y: 260, width: 294, height: 140, axis: "y", force: 0.173 },
  { x: 13649, y: -144, width: 357, height: 90, axis: "x", force: 0.145 },
];

window.lasers = [
  { x: 8316, y: 385, length: 203, width: 4, baseAngle: 5.74, sweepAngle: 0.76, period: 139, blinkPeriod: 0, onRatio: 0.5 },
  { x: 14488, y: -20, length: 110, width: 4, baseAngle: 1.91, sweepAngle: 0, period: 139, blinkPeriod: 92, onRatio: 0.5 },
  { x: 15926, y: 252, length: 135, width: 4, baseAngle: 5.84, sweepAngle: 0.78, period: 139, blinkPeriod: 0, onRatio: 0.5 },
  { x: 17682, y: 352, length: 119, width: 4, baseAngle: 3.05, sweepAngle: 0, period: 139, blinkPeriod: 92, onRatio: 0.5 },
];

window.fallers = [
  { x: 6622, y: 120, size: 57, triggerX: 6417 },
  { x: 10223, y: 60, size: 60, triggerX: 10046 },
  { x: 12532, y: -214, size: 38, triggerX: 12331 },
  { x: 17007, y: 302, size: 29, triggerX: 16845 },
];

window.switches = [
  { x: 2630, y: 13, radius: 26, gateId: "b6_g0" },
];
