// Branch Level "Gilded Vault" (id: b5) — see levels.js's
// TRUE_BRANCH_LEVELS and docs/gameplay.md's "Ten themed branch levels".
// Reachable only from its own Level Map node, never part of the
// sequential 1-100 path — see game.js's startBranchLevelFromOverlay()/
// completeBranchLevel(). Generated by .claude/gen-branch-levels.js;
// re-run audit-gaps.js/audit-checkpoints.js after regenerating.

window.levelText = "Gilded Vault";
window.levelTheme = "gilded";
window.levelBranchId = "b5";

window.platforms = [
  { x: 50, y: 380, width: 260, height: 20 },
  { x: 542, y: 405, width: 163, height: 26 },
  { x: 927, y: 412, width: 231, height: 18, melt: true, meltDelay: 18 },
  { x: 1371, y: 390, width: 116, height: 30 },
  { x: 1646, y: 390, width: 282, height: 24 },
  { x: 2337, y: 313, width: 64, height: 20, moveAxis: "x", moveRange: 151, moveSpeed: 0.063, movePhase: 3.58 },
  { x: 2804, y: 221, width: 151, height: 18, conveyor: true, conveyorSpeed: -1.07 },
  { x: 3111, y: 107, width: 131, height: 15 },
  { x: 3645, y: 13, width: 68, height: 21 },
  { x: 3872, y: 13, width: 349, height: 21 },
  { x: 4643, y: -37, width: 186, height: 22, bounce: true, bounceStrength: -18 },
  { x: 5032, y: -73, width: 108, height: 23 },
  { x: 5368, y: -51, width: 77, height: 14, melt: true, meltDelay: 18 },
  { x: 5604, y: -51, width: 303, height: 26 },
  { x: 6154, y: 16, width: 64, height: 17, moveAxis: "x", moveRange: 87, moveSpeed: 0.048, movePhase: 5.63 },
  { x: 6465, y: 114, width: 122, height: 15, melt: true, meltDelay: 18 },
  { x: 6834, y: 208, width: 66, height: 30, conveyor: true, conveyorSpeed: 1.5 },
  { x: 7059, y: 208, width: 361, height: 17 },
  { x: 7667, y: 291, width: 58, height: 20, bounce: true, bounceStrength: -21 },
  { x: 7972, y: 358, width: 207, height: 24, melt: true, meltDelay: 18 },
  { x: 8417, y: 408, width: 180, height: 31, conveyor: true, conveyorSpeed: -0.91 },
  { x: 8756, y: 408, width: 255, height: 31 },
  { x: 9452, y: 400, width: 138, height: 17 },
  { x: 10018, y: 360, width: 114, height: 25 },
  { x: 10544, y: 285, width: 211, height: 30 },
  { x: 11158, y: 192, width: 105, height: 15 },
  { x: 11422, y: 192, width: 198, height: 18 },
  { x: 12013, y: 81, width: 157, height: 22 },
  { x: 12582, y: 8, width: 157, height: 27, moveAxis: "y", moveRange: 145, moveSpeed: 0.065, movePhase: 6.19 },
  { x: 13151, y: -63, width: 137, height: 25 },
  { x: 13447, y: -63, width: 368, height: 14 },
  { x: 14037, y: -56, width: 218, height: 20, moveAxis: "x", moveRange: 101, moveSpeed: 0.065, movePhase: 2.32 },
  { x: 14483, y: -34, width: 139, height: 21 },
  { x: 14860, y: 10, width: 133, height: 22, bounce: true, bounceStrength: -21 },
  { x: 15240, y: 83, width: 167, height: 20, moveAxis: "y", moveRange: 110, moveSpeed: 0.068, movePhase: 4.2 },
  { x: 15654, y: 172, width: 139, height: 30, melt: true, meltDelay: 18 },
  { x: 15952, y: 172, width: 329, height: 15 },
  { x: 16528, y: 258, width: 155, height: 19 },
  { x: 16930, y: 333, width: 85, height: 23 },
  { x: 17256, y: 387, width: 212, height: 17 },
  { x: 17706, y: 429, width: 96, height: 23, conveyor: true, conveyorSpeed: 1.27 },
  { x: 17982, y: 428, width: 432, height: 20 },
  { x: 2090, y: 363, width: 94, height: 16, gated: true, gateId: "b5_g0" },
  { x: 9189, y: 364, width: 90, height: 16, gated: true, gateId: "b5_g1" },
  { x: 13963, y: -83, width: 95, height: 16, gated: true, gateId: "b5_g2" },
];

window.deadlyPlatforms = [
  { x: 5161, y: -80, width: 96, height: 20 },
  { x: 9616, y: 391, width: 96, height: 20 },
  { x: 10779, y: 278, width: 181, height: 20 },
  { x: 12204, y: 83, width: 109, height: 20 },
  { x: 13309, y: -73, width: 92, height: 20 },
  { x: 17052, y: 326, width: 60, height: 20 },
  { x: 17505, y: 384, width: 133, height: 20 },
];

window.spikes = [
  { x: 3134, y: 107, size: 16 },
  { x: 3150, y: 107, size: 30 },
  { x: 3180, y: 107, size: 34 },
  { x: 9501, y: 400, size: 28 },
  { x: 9529, y: 400, size: 55 },
  { x: 10047, y: 360, size: 36 },
  { x: 11180, y: 192, size: 60 },
  { x: 12048, y: 81, size: 47 },
  { x: 14526, y: -34, size: 38 },
  { x: 16953, y: 333, size: 18 },
  { x: 16971, y: 333, size: 13 },
];

window.checkpoints = [
  { x: 150, y: 350, reached: false },
  { x: 1787, y: 360, reached: false },
  { x: 4047, y: -17, reached: false },
  { x: 5756, y: -81, reached: false },
  { x: 7240, y: 178, reached: false },
  { x: 8884, y: 378, reached: false },
  { x: 11521, y: 162, reached: false },
  { x: 13631, y: -93, reached: false },
  { x: 16117, y: 142, reached: false },
  { x: 18198, y: 398, reached: false }, // Final
];

window.lasers = [
  { x: 1578, y: 343, length: 183, width: 4, baseAngle: 4.46, sweepAngle: 1.02, period: 141, blinkPeriod: 0, onRatio: 0.5 },
  { x: 6672, y: 48, length: 176, width: 4, baseAngle: 6.11, sweepAngle: 0.73, period: 141, blinkPeriod: 0, onRatio: 0.5 },
  { x: 7800, y: 185, length: 149, width: 4, baseAngle: 3.68, sweepAngle: 0.62, period: 141, blinkPeriod: 0, onRatio: 0.5 },
  { x: 8674, y: 312, length: 205, width: 4, baseAngle: 2.17, sweepAngle: 0, period: 141, blinkPeriod: 94, onRatio: 0.5 },
  { x: 16782, y: 200, length: 234, width: 4, baseAngle: 6.25, sweepAngle: 1.04, period: 141, blinkPeriod: 0, onRatio: 0.5 },
];

window.fallers = [
  { x: 5208, y: -211, size: 50, triggerX: 5000 },
  { x: 6980, y: 86, size: 46, triggerX: 6788 },
  { x: 12810, y: -81, size: 45, triggerX: 12647 },
  { x: 15494, y: -65, size: 25, triggerX: 15339 },
  { x: 17082, y: 213, size: 45, triggerX: 16901 },
];

window.switches = [
  { x: 1906, y: 360, radius: 26, gateId: "b5_g0" },
  { x: 8989, y: 378, radius: 26, gateId: "b5_g1" },
  { x: 13793, y: -93, radius: 26, gateId: "b5_g2" },
];

window.portals = [
  { id: "b5_p0a", x: 3942, y: -33, width: 40, height: 46, linkId: "b5_p0b" },
  { id: "b5_p0b", x: 7276, y: 162, width: 40, height: 46, linkId: "b5_p0a" },
  { id: "b5_p1a", x: 8807, y: 362, width: 40, height: 46, linkId: "b5_p1b" },
  { id: "b5_p1b", x: 13668, y: -109, width: 40, height: 46, linkId: "b5_p1a" },
];
