// Branch Level "Aurora Veil" (id: b8) — see levels.js's
// TRUE_BRANCH_LEVELS and docs/gameplay.md's "Ten themed branch levels".
// Reachable only from its own Level Map node, never part of the
// sequential 1-100 path — see game.js's startBranchLevelFromOverlay()/
// completeBranchLevel(). Generated by .claude/gen-branch-levels.js;
// re-run audit-gaps.js/audit-checkpoints.js after regenerating.

window.levelText = "Aurora Veil";
window.levelTheme = "aurora";
window.levelBranchId = "b8";

window.platforms = [
  { x: 50, y: 380, width: 260, height: 20 },
  { x: 732, y: 330, width: 220, height: 22 },
  { x: 1393, y: 329, width: 226, height: 20 },
  { x: 1841, y: 338, width: 57, height: 27, moveAxis: "x", moveRange: 135, moveSpeed: 0.048, movePhase: 0.16 },
  { x: 2136, y: 384, width: 165, height: 25, melt: true, meltDelay: 18 },
  { x: 2460, y: 384, width: 412, height: 24 },
  { x: 3119, y: 489, width: 120, height: 20, moveAxis: "x", moveRange: 106, moveSpeed: 0.055, movePhase: 2.71 },
  { x: 3486, y: 590, width: 54, height: 20, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 3787, y: 692, width: 230, height: 23, moveAxis: "y", moveRange: 102, moveSpeed: 0.044, movePhase: 0.36 },
  { x: 4264, y: 769, width: 193, height: 18, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 4616, y: 769, width: 215, height: 29 },
  { x: 5063, y: 803, width: 186, height: 17 },
  { x: 5471, y: 806, width: 124, height: 25 },
  { x: 6032, y: 790, width: 114, height: 22 },
  { x: 6564, y: 733, width: 242, height: 17, melt: true, meltDelay: 18 },
  { x: 6965, y: 733, width: 292, height: 22 },
  { x: 7428, y: 638, width: 87, height: 28 },
  { x: 7696, y: 554, width: 95, height: 26 },
  { x: 8184, y: 448, width: 209, height: 18, bounce: true, bounceStrength: -17 },
  { x: 8805, y: 380, width: 168, height: 21 },
  { x: 9163, y: 314, width: 211, height: 26 },
  { x: 9533, y: 314, width: 288, height: 29 },
  { x: 10049, y: 332, width: 109, height: 29, melt: true, meltDelay: 18 },
  { x: 10396, y: 380, width: 100, height: 31 },
  { x: 10743, y: 456, width: 85, height: 29, moveAxis: "x", moveRange: 85, moveSpeed: 0.058, movePhase: 0.63 },
  { x: 10987, y: 456, width: 295, height: 20 },
  { x: 11529, y: 557, width: 139, height: 17, moveAxis: "x", moveRange: 119, moveSpeed: 0.044, movePhase: 3.96 },
  { x: 11915, y: 665, width: 183, height: 22 },
  { x: 12345, y: 761, width: 139, height: 26, melt: true, meltDelay: 18 },
  { x: 12643, y: 761, width: 316, height: 17 },
  { x: 13200, y: 822, width: 93, height: 16, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 13525, y: 856, width: 222, height: 14 },
  { x: 14178, y: 829, width: 65, height: 24 },
  { x: 14402, y: 829, width: 274, height: 21 },
  { x: 15088, y: 761, width: 210, height: 25 },
  { x: 15463, y: 658, width: 158, height: 25, melt: true, meltDelay: 18 },
  { x: 16020, y: 555, width: 106, height: 30 },
  { x: 16285, y: 555, width: 391, height: 23 },
  { x: 17075, y: 458, width: 214, height: 14, moveAxis: "x", moveRange: 115, moveSpeed: 0.051, movePhase: 4.62 },
  { x: 17711, y: 405, width: 139, height: 18 },
  { x: 18044, y: 351, width: 71, height: 27 },
  { x: 18337, y: 352, width: 94, height: 16 },
  { x: 18591, y: 346, width: 409, height: 20 },
];

window.deadlyPlatforms = [
  { x: 11602, y: 611, width: 89, height: 25, moveAxis: "y", moveRange: 95, moveSpeed: 0.047, movePhase: 4.58 },
  { x: 1639, y: 334, width: 162, height: 20 },
  { x: 5628, y: 812, width: 67, height: 20 },
  { x: 6181, y: 798, width: 88, height: 20 },
  { x: 7819, y: 559, width: 60, height: 20 },
  { x: 9009, y: 379, width: 132, height: 20 },
  { x: 10532, y: 384, width: 60, height: 20 },
  { x: 17887, y: 401, width: 75, height: 20 },
];

window.spikes = [
  { x: 1446, y: 329, size: 50 },
  { x: 1496, y: 329, size: 51 },
  { x: 1547, y: 329, size: 31 },
  { x: 6066, y: 790, size: 48 },
  { x: 7445, y: 638, size: 18 },
  { x: 7463, y: 638, size: 24 },
  { x: 13604, y: 856, size: 12 },
  { x: 15154, y: 761, size: 26 },
  { x: 15180, y: 761, size: 41 },
  { x: 15221, y: 761, size: 47 },
  { x: 16041, y: 555, size: 26 },
  { x: 16067, y: 555, size: 37 },
  { x: 17751, y: 405, size: 35 },
  { x: 18063, y: 351, size: 17 },
  { x: 18352, y: 352, size: 16 },
  { x: 18368, y: 352, size: 30 },
];

window.checkpoints = [
  { x: 150, y: 350, reached: false },
  { x: 2666, y: 354, reached: false },
  { x: 4724, y: 739, reached: false },
  { x: 7111, y: 703, reached: false },
  { x: 9677, y: 284, reached: false },
  { x: 11135, y: 426, reached: false },
  { x: 12801, y: 731, reached: false },
  { x: 14539, y: 799, reached: false },
  { x: 16481, y: 525, reached: false },
  { x: 18796, y: 316, reached: false }, // Final
];

window.forceZones = [
  { x: 2470, y: 294, width: 392, height: 90, axis: "x", force: 0.176 },
  { x: 9539, y: 174, width: 276, height: 140, axis: "y", force: 0.18 },
  { x: 12653, y: 671, width: 296, height: 90, axis: "x", force: -0.16 },
  { x: 16295, y: 465, width: 371, height: 90, axis: "x", force: 0.179 },
];

window.lasers = [
  { x: 1702, y: 280, length: 193, width: 4, baseAngle: 6, sweepAngle: 0, period: 144, blinkPeriod: 96, onRatio: 0.5 },
  { x: 8479, y: 399, length: 271, width: 4, baseAngle: 0.51, sweepAngle: 0, period: 144, blinkPeriod: 96, onRatio: 0.5 },
  { x: 15715, y: 601, length: 187, width: 4, baseAngle: 5.32, sweepAngle: 0, period: 144, blinkPeriod: 96, onRatio: 0.5 },
];

window.fallers = [
  { x: 3604, y: 490, size: 26, triggerX: 3411 },
  { x: 4104, y: 590, size: 53, triggerX: 3927 },
  { x: 6874, y: 592, size: 47, triggerX: 6733 },
  { x: 10913, y: 334, size: 47, triggerX: 10778 },
  { x: 13814, y: 718, size: 47, triggerX: 13598 },
];

window.portals = [
  { id: "b8_p0a", x: 4659, y: 723, width: 40, height: 46, linkId: "b8_p0b" },
  { id: "b8_p0b", x: 9706, y: 268, width: 40, height: 46, linkId: "b8_p0a" },
  { id: "b8_p1a", x: 11046, y: 410, width: 40, height: 46, linkId: "b8_p1b" },
  { id: "b8_p1b", x: 14566, y: 783, width: 40, height: 46, linkId: "b8_p1a" },
];
