// Branch Level "Crimson Bastion" (id: b7) — see levels.js's
// TRUE_BRANCH_LEVELS and docs/gameplay.md's "Ten themed branch levels".
// Reachable only from its own Level Map node, never part of the
// sequential 1-100 path — see game.js's startBranchLevelFromOverlay()/
// completeBranchLevel(). Generated by .claude/gen-branch-levels.js;
// re-run audit-gaps.js/audit-checkpoints.js after regenerating.

window.levelText = "Crimson Bastion";
window.levelTheme = "crimson";
window.levelBranchId = "b7";

window.platforms = [
  { x: 50, y: 380, width: 260, height: 20 },
  { x: 709, y: 281, width: 135, height: 16, moveAxis: "y", moveRange: 168, moveSpeed: 0.065, movePhase: 4.28 },
  { x: 1025, y: 199, width: 52, height: 28 },
  { x: 1267, y: 132, width: 211, height: 24, moveAxis: "x", moveRange: 100, moveSpeed: 0.055, movePhase: 1.09 },
  { x: 1896, y: 69, width: 152, height: 30 },
  { x: 2207, y: 69, width: 342, height: 29 },
  { x: 2777, y: 82, width: 64, height: 26 },
  { x: 3082, y: 144, width: 249, height: 22 },
  { x: 3578, y: 226, width: 195, height: 16, moveAxis: "y", moveRange: 92, moveSpeed: 0.05, movePhase: 1.57 },
  { x: 4020, y: 340, width: 143, height: 20 },
  { x: 4322, y: 340, width: 330, height: 20 },
  { x: 4899, y: 445, width: 230, height: 28 },
  { x: 5376, y: 540, width: 162, height: 24, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 5779, y: 601, width: 177, height: 17, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 6197, y: 654, width: 120, height: 20, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 6476, y: 654, width: 397, height: 21 },
  { x: 7314, y: 643, width: 189, height: 28, moveAxis: "y", moveRange: 97, moveSpeed: 0.071, movePhase: 0.65 },
  { x: 7925, y: 595, width: 178, height: 15 },
  { x: 8512, y: 518, width: 119, height: 21 },
  { x: 8802, y: 419, width: 230, height: 29, moveAxis: "x", moveRange: 107, moveSpeed: 0.058, movePhase: 1.83 },
  { x: 9191, y: 419, width: 237, height: 25 },
  { x: 9580, y: 300, width: 82, height: 28, moveAxis: "x", moveRange: 132, moveSpeed: 0.052, movePhase: 4.56 },
  { x: 10061, y: 197, width: 121, height: 29, moveAxis: "x", moveRange: 152, moveSpeed: 0.046, movePhase: 5.01 },
  { x: 10376, y: 140, width: 122, height: 16, bounce: true, bounceStrength: -18 },
  { x: 10698, y: 91, width: 75, height: 30, bounce: true, bounceStrength: -22 },
  { x: 10995, y: 100, width: 179, height: 16, moveAxis: "x", moveRange: 115, moveSpeed: 0.046, movePhase: 0.43 },
  { x: 11333, y: 100, width: 285, height: 21 },
  { x: 11865, y: 172, width: 189, height: 17, melt: true, meltDelay: 18 },
  { x: 12301, y: 260, width: 161, height: 29, moveAxis: "x", moveRange: 136, moveSpeed: 0.049, movePhase: 5.01 },
  { x: 12709, y: 350, width: 100, height: 27 },
  { x: 13056, y: 470, width: 223, height: 15, conveyor: true, conveyorSpeed: -1.11 },
  { x: 13438, y: 470, width: 253, height: 14 },
  { x: 13938, y: 567, width: 177, height: 27 },
  { x: 14362, y: 632, width: 208, height: 23 },
  { x: 14802, y: 660, width: 194, height: 30 },
  { x: 15215, y: 651, width: 242, height: 19, moveAxis: "x", moveRange: 151, moveSpeed: 0.056, movePhase: 2.48 },
  { x: 15879, y: 604, width: 223, height: 29, moveAxis: "x", moveRange: 159, moveSpeed: 0.052, movePhase: 0.49 },
  { x: 16261, y: 604, width: 333, height: 25 },
  { x: 16993, y: 500, width: 95, height: 18, moveAxis: "y", moveRange: 97, moveSpeed: 0.051, movePhase: 2.78 },
  { x: 17234, y: 378, width: 147, height: 18, moveAxis: "y", moveRange: 110, moveSpeed: 0.058, movePhase: 4.24 },
  { x: 17552, y: 284, width: 63, height: 24, moveAxis: "x", moveRange: 115, moveSpeed: 0.047, movePhase: 6.23 },
  { x: 17774, y: 284, width: 199, height: 31 },
  { x: 18382, y: 204, width: 160, height: 24 },
  { x: 18708, y: 202, width: 411, height: 20 },
  { x: 9605, y: 380, width: 115, height: 16, gated: true, gateId: "b7_g0" },
];

window.deadlyPlatforms = [
  { x: 784, y: 217, width: 75, height: 17, moveAxis: "x", moveRange: 128, moveSpeed: 0.076, movePhase: 2.16 },
  { x: 1196, y: 106, width: 162, height: 18, moveAxis: "y", moveRange: 87, moveSpeed: 0.05, movePhase: 3.24 },
  { x: 7358, y: 684, width: 124, height: 20, moveAxis: "x", moveRange: 106, moveSpeed: 0.07, movePhase: 4.34 },
  { x: 8737, y: 377, width: 161, height: 17, moveAxis: "y", moveRange: 99, moveSpeed: 0.072, movePhase: 4.66 },
  { x: 9505, y: 244, width: 67, height: 14, moveAxis: "y", moveRange: 147, moveSpeed: 0.051, movePhase: 3.93 },
  { x: 12395, y: 232, width: 124, height: 18, moveAxis: "y", moveRange: 110, moveSpeed: 0.059, movePhase: 5.77 },
  { x: 17185, y: 337, width: 91, height: 17, moveAxis: "x", moveRange: 116, moveSpeed: 0.05, movePhase: 1.78 },
  { x: 2871, y: 85, width: 60, height: 20 },
  { x: 3362, y: 147, width: 158, height: 20 },
  { x: 5150, y: 442, width: 137, height: 20 },
  { x: 12836, y: 345, width: 60, height: 20 },
  { x: 15026, y: 667, width: 101, height: 20 },
  { x: 18575, y: 207, width: 134, height: 20 },
];

window.spikes = [
  { x: 1033, y: 199, size: 14 },
  { x: 1047, y: 199, size: 24 },
  { x: 1931, y: 69, size: 20 },
  { x: 1951, y: 69, size: 46 },
  { x: 3166, y: 144, size: 24 },
  { x: 3190, y: 144, size: 24 },
  { x: 3214, y: 144, size: 41 },
  { x: 3255, y: 144, size: 25 },
  { x: 7959, y: 595, size: 48 },
  { x: 8007, y: 595, size: 31 },
  { x: 8038, y: 595, size: 44 },
  { x: 12721, y: 350, size: 44 },
  { x: 12765, y: 350, size: 37 },
  { x: 14401, y: 632, size: 60 },
  { x: 14461, y: 632, size: 35 },
  { x: 14496, y: 632, size: 63 },
  { x: 14849, y: 660, size: 27 },
  { x: 18411, y: 204, size: 19 },
  { x: 18430, y: 204, size: 61 },
];

window.checkpoints = [
  { x: 150, y: 350, reached: false },
  { x: 2378, y: 39, reached: false },
  { x: 4487, y: 310, reached: false },
  { x: 6675, y: 624, reached: false },
  { x: 9310, y: 389, reached: false },
  { x: 11476, y: 70, reached: false },
  { x: 13565, y: 440, reached: false },
  { x: 16428, y: 574, reached: false },
  { x: 17874, y: 254, reached: false },
  { x: 18914, y: 172, reached: false }, // Final
];

window.forceZones = [
  { x: 2217, y: -21, width: 322, height: 90, axis: "x", force: -0.204 },
];

window.lasers = [
  { x: 919, y: 235, length: 179, width: 4, baseAngle: 5.35, sweepAngle: 0.93, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 1160, y: 96, length: 189, width: 4, baseAngle: 4.94, sweepAngle: 0, period: 133, blinkPeriod: 87, onRatio: 0.5 },
  { x: 1567, y: 72, length: 136, width: 4, baseAngle: 4.47, sweepAngle: 0.72, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 2145, y: -40, length: 260, width: 4, baseAngle: 0.39, sweepAngle: 0.6, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 2937, y: -9, length: 115, width: 4, baseAngle: 3.85, sweepAngle: 0.57, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 3414, y: 89, length: 254, width: 4, baseAngle: 1.69, sweepAngle: 0.73, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 3833, y: 170, length: 150, width: 4, baseAngle: 3.27, sweepAngle: 1.12, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 4242, y: 254, length: 148, width: 4, baseAngle: 2.31, sweepAngle: 0.76, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 8195, y: 524, length: 176, width: 4, baseAngle: 5.95, sweepAngle: 0.48, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 9126, y: 322, length: 188, width: 4, baseAngle: 5.01, sweepAngle: 0.94, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 9739, y: 203, length: 163, width: 4, baseAngle: 0.12, sweepAngle: 0.93, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 10270, y: 110, length: 274, width: 4, baseAngle: 1.36, sweepAngle: 0.75, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 10595, y: 65, length: 119, width: 4, baseAngle: 4.2, sweepAngle: 0, period: 133, blinkPeriod: 87, onRatio: 0.5 },
  { x: 10870, y: 19, length: 179, width: 4, baseAngle: 6.01, sweepAngle: 0.58, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 11239, y: 9, length: 126, width: 4, baseAngle: 0.67, sweepAngle: 0, period: 133, blinkPeriod: 87, onRatio: 0.5 },
  { x: 12148, y: 102, length: 280, width: 4, baseAngle: 2.06, sweepAngle: 0.78, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 13367, y: 361, length: 194, width: 4, baseAngle: 6.24, sweepAngle: 0, period: 133, blinkPeriod: 87, onRatio: 0.5 },
  { x: 14179, y: 458, length: 192, width: 4, baseAngle: 4.92, sweepAngle: 0, period: 133, blinkPeriod: 87, onRatio: 0.5 },
  { x: 15538, y: 579, length: 130, width: 4, baseAngle: 1.86, sweepAngle: 0, period: 133, blinkPeriod: 87, onRatio: 0.5 },
  { x: 16196, y: 498, length: 208, width: 4, baseAngle: 4.87, sweepAngle: 1.14, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 17463, y: 303, length: 173, width: 4, baseAngle: 4.33, sweepAngle: 0.84, period: 133, blinkPeriod: 0, onRatio: 0.5 },
  { x: 18640, y: 135, length: 171, width: 4, baseAngle: 5.01, sweepAngle: 0.55, period: 133, blinkPeriod: 0, onRatio: 0.5 },
];

window.fallers = [
  { x: 6037, y: 508, size: 40, triggerX: 5855 },
];

window.switches = [
  { x: 9406, y: 389, radius: 26, gateId: "b7_g0" },
];
