// Branch Level "Storm Reach" (id: b4) — see levels.js's
// TRUE_BRANCH_LEVELS and docs/gameplay.md's "Ten themed branch levels".
// Reachable only from its own Level Map node, never part of the
// sequential 1-100 path — see game.js's startBranchLevelFromOverlay()/
// completeBranchLevel(). Generated by .claude/gen-branch-levels.js;
// re-run audit-gaps.js/audit-checkpoints.js after regenerating.

window.levelText = "Storm Reach";
window.levelTheme = "storm";
window.levelBranchId = "b4";

window.platforms = [
  { x: 50, y: 380, width: 260, height: 20 },
  { x: 557, y: 487, width: 177, height: 23 },
  { x: 981, y: 572, width: 124, height: 28, moveAxis: "y", moveRange: 118, moveSpeed: 0.06, movePhase: 1.62 },
  { x: 1346, y: 623, width: 116, height: 26, moveAxis: "x", moveRange: 117, moveSpeed: 0.057, movePhase: 0.86 },
  { x: 1621, y: 623, width: 285, height: 18 },
  { x: 2128, y: 629, width: 66, height: 26 },
  { x: 2394, y: 585, width: 189, height: 20, melt: true, meltDelay: 18 },
  { x: 3005, y: 537, width: 186, height: 14, bounce: true, bounceStrength: -18 },
  { x: 3350, y: 537, width: 263, height: 30 },
  { x: 3769, y: 423, width: 145, height: 18 },
  { x: 4066, y: 306, width: 190, height: 19 },
  { x: 4418, y: 197, width: 188, height: 19, moveAxis: "y", moveRange: 149, moveSpeed: 0.061, movePhase: 1.35 },
  { x: 5005, y: 101, width: 173, height: 19 },
  { x: 5337, y: 101, width: 208, height: 31 },
  { x: 5976, y: 77, width: 77, height: 28, moveAxis: "y", moveRange: 144, moveSpeed: 0.054, movePhase: 5.82 },
  { x: 6275, y: 80, width: 195, height: 19 },
  { x: 6708, y: 130, width: 126, height: 22, melt: true, meltDelay: 18 },
  { x: 7075, y: 183, width: 107, height: 20 },
  { x: 7341, y: 183, width: 378, height: 17 },
  { x: 7966, y: 294, width: 55, height: 19, melt: true, meltDelay: 18 },
  { x: 8268, y: 395, width: 50, height: 24 },
  { x: 8565, y: 499, width: 190, height: 21, moveAxis: "y", moveRange: 127, moveSpeed: 0.044, movePhase: 1.37 },
  { x: 8914, y: 499, width: 303, height: 30 },
  { x: 9458, y: 562, width: 113, height: 22, moveAxis: "y", moveRange: 102, moveSpeed: 0.05, movePhase: 3.43 },
  { x: 9799, y: 579, width: 185, height: 24, conveyor: true, conveyorSpeed: 1.83 },
  { x: 10425, y: 576, width: 80, height: 26, conveyor: true, conveyorSpeed: 1.46 },
  { x: 10933, y: 533, width: 86, height: 15 },
  { x: 11209, y: 468, width: 65, height: 19, moveAxis: "x", moveRange: 90, moveSpeed: 0.051, movePhase: 5.88 },
  { x: 11433, y: 468, width: 346, height: 20 },
  { x: 11941, y: 358, width: 137, height: 21 },
  { x: 12234, y: 244, width: 211, height: 18, melt: true, meltDelay: 18 },
  { x: 12844, y: 140, width: 107, height: 16, moveAxis: "x", moveRange: 158, moveSpeed: 0.047, movePhase: 0.07 },
  { x: 13360, y: 62, width: 107, height: 15 },
  { x: 13626, y: 62, width: 309, height: 21 },
  { x: 14157, y: 65, width: 98, height: 16, moveAxis: "x", moveRange: 120, moveSpeed: 0.053, movePhase: 2.15 },
  { x: 14487, y: 98, width: 101, height: 18, moveAxis: "y", moveRange: 116, moveSpeed: 0.058, movePhase: 1.09 },
  { x: 14835, y: 166, width: 246, height: 17, moveAxis: "x", moveRange: 104, moveSpeed: 0.057, movePhase: 4.2 },
  { x: 15240, y: 166, width: 290, height: 15 },
  { x: 15777, y: 278, width: 166, height: 25, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 16190, y: 374, width: 212, height: 26, moveAxis: "x", moveRange: 147, moveSpeed: 0.069, movePhase: 1.32 },
  { x: 16649, y: 466, width: 208, height: 19, moveAxis: "x", moveRange: 108, moveSpeed: 0.06, movePhase: 2.53 },
  { x: 17016, y: 466, width: 197, height: 28 },
  { x: 17454, y: 522, width: 89, height: 14, moveAxis: "x", moveRange: 120, moveSpeed: 0.06, movePhase: 5.36 },
  { x: 17781, y: 560, width: 67, height: 22, moveAxis: "y", moveRange: 155, moveSpeed: 0.068, movePhase: 0.26 },
  { x: 18041, y: 570, width: 419, height: 20 },
];

window.deadlyPlatforms = [
  { x: 4370, y: 257, width: 114, height: 17, moveAxis: "x", moveRange: 152, moveSpeed: 0.066, movePhase: 5.33 },
  { x: 8491, y: 453, width: 107, height: 17, moveAxis: "x", moveRange: 107, moveSpeed: 0.044, movePhase: 1.89 },
  { x: 9410, y: 509, width: 66, height: 20, moveAxis: "x", moveRange: 108, moveSpeed: 0.06, movePhase: 6.24 },
  { x: 11141, y: 406, width: 50, height: 19, moveAxis: "y", moveRange: 107, moveSpeed: 0.046, movePhase: 2.45 },
  { x: 16714, y: 504, width: 171, height: 19, moveAxis: "y", moveRange: 113, moveSpeed: 0.055, movePhase: 6.13 },
  { x: 17374, y: 484, width: 50, height: 21, moveAxis: "y", moveRange: 113, moveSpeed: 0.056, movePhase: 4.49 },
  { x: 767, y: 482, width: 130, height: 20 },
  { x: 2216, y: 625, width: 60, height: 20 },
  { x: 4279, y: 300, width: 132, height: 20 },
  { x: 6499, y: 79, width: 146, height: 20 },
  { x: 7203, y: 187, width: 74, height: 20 },
  { x: 11058, y: 540, width: 60, height: 20 },
  { x: 12116, y: 357, width: 112, height: 20 },
];

window.spikes = [
  { x: 2148, y: 629, size: 31 },
  { x: 4100, y: 306, size: 40 },
  { x: 6316, y: 80, size: 53 },
  { x: 10954, y: 533, size: 15 },
  { x: 10969, y: 533, size: 12 },
  { x: 11970, y: 358, size: 53 },
  { x: 13374, y: 62, size: 19 },
  { x: 13393, y: 62, size: 48 },
];

window.checkpoints = [
  { x: 150, y: 350, reached: false },
  { x: 1764, y: 593, reached: false },
  { x: 3482, y: 507, reached: false },
  { x: 5441, y: 71, reached: false },
  { x: 7530, y: 153, reached: false },
  { x: 9066, y: 469, reached: false },
  { x: 11606, y: 438, reached: false },
  { x: 13781, y: 32, reached: false },
  { x: 15385, y: 136, reached: false },
  { x: 17115, y: 436, reached: false },
  { x: 18251, y: 540, reached: false }, // Final
];

window.forceZones = [
  { x: 1627, y: 483, width: 273, height: 140, axis: "y", force: 0.136 },
  { x: 3360, y: 447, width: 243, height: 90, axis: "x", force: 0.2 },
  { x: 7347, y: 43, width: 366, height: 140, axis: "y", force: 0.129 },
  { x: 15246, y: 26, width: 278, height: 140, axis: "y", force: 0.147 },
];

window.lasers = [
  { x: 798, y: 388, length: 124, width: 4, baseAngle: 5.9, sweepAngle: 0.79, period: 139, blinkPeriod: 0, onRatio: 0.5 },
  { x: 1170, y: 506, length: 165, width: 4, baseAngle: 6.26, sweepAngle: 1.16, period: 139, blinkPeriod: 0, onRatio: 0.5 },
  { x: 1526, y: 518, length: 205, width: 4, baseAngle: 0.91, sweepAngle: 1.06, period: 139, blinkPeriod: 0, onRatio: 0.5 },
  { x: 6108, y: -26, length: 209, width: 4, baseAngle: 4.28, sweepAngle: 0, period: 139, blinkPeriod: 92, onRatio: 0.5 },
  { x: 6923, y: 49, length: 144, width: 4, baseAngle: 5.74, sweepAngle: 0, period: 139, blinkPeriod: 92, onRatio: 0.5 },
  { x: 8111, y: 218, length: 228, width: 4, baseAngle: 6.19, sweepAngle: 0.83, period: 139, blinkPeriod: 0, onRatio: 0.5 },
  { x: 10596, y: 522, length: 157, width: 4, baseAngle: 3.6, sweepAngle: 0, period: 139, blinkPeriod: 92, onRatio: 0.5 },
  { x: 11091, y: 462, length: 229, width: 4, baseAngle: 4.84, sweepAngle: 0.88, period: 139, blinkPeriod: 0, onRatio: 0.5 },
  { x: 11357, y: 412, length: 180, width: 4, baseAngle: 5.18, sweepAngle: 0, period: 139, blinkPeriod: 92, onRatio: 0.5 },
  { x: 12538, y: 171, length: 261, width: 4, baseAngle: 0.34, sweepAngle: 0.7, period: 139, blinkPeriod: 0, onRatio: 0.5 },
  { x: 17618, y: 480, length: 121, width: 4, baseAngle: 5.51, sweepAngle: 0.77, period: 139, blinkPeriod: 0, onRatio: 0.5 },
  { x: 17921, y: 508, length: 257, width: 4, baseAngle: 4.86, sweepAngle: 1.08, period: 139, blinkPeriod: 0, onRatio: 0.5 },
];

window.fallers = [
  { x: 2650, y: 488, size: 30, triggerX: 2447 },
  { x: 3281, y: 434, size: 46, triggerX: 3126 },
  { x: 3995, y: 307, size: 42, triggerX: 3781 },
  { x: 4691, y: 77, size: 59, triggerX: 4534 },
];
