// Branch Level "Solar Crown" (id: b10) — see levels.js's
// TRUE_BRANCH_LEVELS and docs/gameplay.md's "Ten themed branch levels".
// Reachable only from its own Level Map node, never part of the
// sequential 1-100 path — see game.js's startBranchLevelFromOverlay()/
// completeBranchLevel(). Generated by .claude/gen-branch-levels.js;
// re-run audit-gaps.js/audit-checkpoints.js after regenerating.

window.levelText = "Solar Crown";
window.levelTheme = "solar";
window.levelBranchId = "b10";

window.platforms = [
  { x: 50, y: 380, width: 260, height: 20 },
  { x: 557, y: 485, width: 119, height: 17, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 923, y: 608, width: 154, height: 25, moveAxis: "y", moveRange: 143, moveSpeed: 0.062, movePhase: 3.06 },
  { x: 1324, y: 702, width: 176, height: 25, moveAxis: "x", moveRange: 162, moveSpeed: 0.064, movePhase: 2.48 },
  { x: 1747, y: 778, width: 93, height: 16, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 1999, y: 778, width: 229, height: 28 },
  { x: 2450, y: 780, width: 118, height: 26, bounce: true, bounceStrength: -17 },
  { x: 2999, y: 755, width: 222, height: 31, moveAxis: "x", moveRange: 100, moveSpeed: 0.07, movePhase: 2.56 },
  { x: 3405, y: 677, width: 210, height: 14, moveAxis: "y", moveRange: 176, moveSpeed: 0.072, movePhase: 2.59 },
  { x: 4018, y: 585, width: 213, height: 27 },
  { x: 4624, y: 477, width: 242, height: 15 },
  { x: 5025, y: 477, width: 379, height: 17 },
  { x: 5807, y: 382, width: 200, height: 29 },
  { x: 6410, y: 289, width: 182, height: 14, bounce: true, bounceStrength: -17 },
  { x: 7004, y: 216, width: 199, height: 23, bounce: true, bounceStrength: -19 },
  { x: 7412, y: 185, width: 205, height: 23, conveyor: true, conveyorSpeed: -0.93 },
  { x: 7776, y: 185, width: 258, height: 29 },
  { x: 8275, y: 248, width: 196, height: 17, moveAxis: "x", moveRange: 125, moveSpeed: 0.055, movePhase: 2.96 },
  { x: 8718, y: 337, width: 124, height: 24, moveAxis: "y", moveRange: 159, moveSpeed: 0.064, movePhase: 2.34 },
  { x: 9089, y: 434, width: 247, height: 28, conveyor: true, conveyorSpeed: 1.81 },
  { x: 9583, y: 531, width: 140, height: 22, moveAxis: "x", moveRange: 127, moveSpeed: 0.061, movePhase: 1.68 },
  { x: 9882, y: 531, width: 357, height: 31 },
  { x: 10486, y: 631, width: 105, height: 18, melt: true, meltDelay: 18 },
  { x: 10838, y: 727, width: 198, height: 28, melt: true, meltDelay: 18 },
  { x: 11277, y: 784, width: 64, height: 23, conveyor: true, conveyorSpeed: 2.12 },
  { x: 11569, y: 796, width: 90, height: 27, bounce: true, bounceStrength: -20 },
  { x: 11818, y: 796, width: 298, height: 20 },
  { x: 12534, y: 736, width: 218, height: 14, bounce: true, bounceStrength: -21 },
  { x: 13161, y: 651, width: 73, height: 28, melt: true, meltDelay: 18 },
  { x: 13627, y: 539, width: 200, height: 30 },
  { x: 14226, y: 440, width: 66, height: 25, moveAxis: "y", moveRange: 111, moveSpeed: 0.053, movePhase: 0.64 },
  { x: 14691, y: 339, width: 83, height: 22 },
  { x: 14933, y: 339, width: 346, height: 31 },
  { x: 15691, y: 268, width: 55, height: 23, bounce: true, bounceStrength: -21 },
  { x: 15946, y: 223, width: 143, height: 20 },
  { x: 16526, y: 210, width: 231, height: 14, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 16995, y: 257, width: 173, height: 17 },
  { x: 17415, y: 331, width: 206, height: 24, moveAxis: "x", moveRange: 106, moveSpeed: 0.063, movePhase: 2.57 },
  { x: 17780, y: 331, width: 344, height: 14 },
  { x: 18371, y: 435, width: 237, height: 17, moveAxis: "x", moveRange: 114, moveSpeed: 0.069, movePhase: 1.14 },
  { x: 18855, y: 550, width: 81, height: 22, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 19183, y: 672, width: 52, height: 28 },
  { x: 19394, y: 672, width: 330, height: 17 },
  { x: 19971, y: 752, width: 70, height: 18 },
  { x: 20269, y: 772, width: 173, height: 27, bounce: true, bounceStrength: -18 },
  { x: 20664, y: 778, width: 230, height: 25, melt: true, meltDelay: 18 },
  { x: 21322, y: 736, width: 236, height: 20 },
  { x: 21976, y: 671, width: 101, height: 29, moveAxis: "x", moveRange: 134, moveSpeed: 0.053, movePhase: 3.53 },
  { x: 22236, y: 671, width: 305, height: 25 },
  { x: 22711, y: 665, width: 436, height: 20 },
  { x: 5592, y: 456, width: 97, height: 16, gated: true, gateId: "b10_g0" },
  { x: 19906, y: 646, width: 101, height: 16, gated: true, gateId: "b10_g1" },
];

window.deadlyPlatforms = [
  { x: 1010, y: 672, width: 122, height: 19, moveAxis: "x", moveRange: 110, moveSpeed: 0.057, movePhase: 3.38 },
  { x: 3449, y: 715, width: 154, height: 25, moveAxis: "x", moveRange: 204, moveSpeed: 0.071, movePhase: 5.83 },
  { x: 8335, y: 199, width: 128, height: 18, moveAxis: "y", moveRange: 110, moveSpeed: 0.069, movePhase: 6.19 },
  { x: 9493, y: 577, width: 104, height: 17, moveAxis: "y", moveRange: 112, moveSpeed: 0.068, movePhase: 0.71 },
  { x: 14157, y: 503, width: 56, height: 23, moveAxis: "x", moveRange: 108, moveSpeed: 0.063, movePhase: 5.67 },
  { x: 4260, y: 585, width: 119, height: 20 },
  { x: 4896, y: 477, width: 146, height: 20 },
  { x: 6039, y: 380, width: 155, height: 20 },
  { x: 16119, y: 232, width: 127, height: 20 },
  { x: 17203, y: 250, width: 149, height: 20 },
  { x: 19255, y: 668, width: 60, height: 20 },
];

window.spikes = [
  { x: 4048, y: 585, size: 25 },
  { x: 4073, y: 585, size: 42 },
  { x: 4115, y: 585, size: 27 },
  { x: 4142, y: 585, size: 36 },
  { x: 4688, y: 477, size: 28 },
  { x: 14717, y: 339, size: 43 },
  { x: 15985, y: 223, size: 58 },
  { x: 17041, y: 257, size: 38 },
  { x: 17079, y: 257, size: 49 },
  { x: 17128, y: 257, size: 34 },
];

window.checkpoints = [
  { x: 150, y: 350, reached: false },
  { x: 2114, y: 748, reached: false },
  { x: 5215, y: 447, reached: false },
  { x: 7905, y: 155, reached: false },
  { x: 10061, y: 501, reached: false },
  { x: 11967, y: 766, reached: false },
  { x: 15106, y: 309, reached: false },
  { x: 17952, y: 301, reached: false },
  { x: 19559, y: 642, reached: false },
  { x: 22389, y: 641, reached: false },
  { x: 22929, y: 635, reached: false }, // Final
];

window.forceZones = [
  { x: 19404, y: 582, width: 310, height: 90, axis: "x", force: -0.191 },
];

window.lasers = [
  { x: 1918, y: 703, length: 162, width: 4, baseAngle: 0.62, sweepAngle: 1.05, period: 125, blinkPeriod: 0, onRatio: 0.5 },
  { x: 2664, y: 702, length: 166, width: 4, baseAngle: 1.58, sweepAngle: 0.72, period: 125, blinkPeriod: 0, onRatio: 0.5 },
  { x: 4958, y: 371, length: 141, width: 4, baseAngle: 4.2, sweepAngle: 0, period: 125, blinkPeriod: 80, onRatio: 0.5 },
  { x: 7262, y: 139, length: 269, width: 4, baseAngle: 4.05, sweepAngle: 0, period: 125, blinkPeriod: 80, onRatio: 0.5 },
  { x: 9400, y: 391, length: 167, width: 4, baseAngle: 3.78, sweepAngle: 0, period: 125, blinkPeriod: 80, onRatio: 0.5 },
  { x: 11104, y: 626, length: 223, width: 4, baseAngle: 4.07, sweepAngle: 0.57, period: 125, blinkPeriod: 0, onRatio: 0.5 },
  { x: 11720, y: 739, length: 241, width: 4, baseAngle: 0.01, sweepAngle: 0.53, period: 125, blinkPeriod: 0, onRatio: 0.5 },
  { x: 12807, y: 656, length: 201, width: 4, baseAngle: 1.37, sweepAngle: 1.01, period: 125, blinkPeriod: 0, onRatio: 0.5 },
  { x: 13295, y: 607, length: 189, width: 4, baseAngle: 3.1, sweepAngle: 0.6, period: 125, blinkPeriod: 0, onRatio: 0.5 },
  { x: 14359, y: 354, length: 132, width: 4, baseAngle: 5.58, sweepAngle: 0, period: 125, blinkPeriod: 80, onRatio: 0.5 },
  { x: 16845, y: 144, length: 141, width: 4, baseAngle: 5.85, sweepAngle: 0.53, period: 125, blinkPeriod: 0, onRatio: 0.5 },
  { x: 20140, y: 712, length: 144, width: 4, baseAngle: 5.63, sweepAngle: 0, period: 125, blinkPeriod: 80, onRatio: 0.5 },
  { x: 20526, y: 724, length: 247, width: 4, baseAngle: 0.96, sweepAngle: 0, period: 125, blinkPeriod: 80, onRatio: 0.5 },
  { x: 20954, y: 682, length: 264, width: 4, baseAngle: 2.25, sweepAngle: 0, period: 125, blinkPeriod: 80, onRatio: 0.5 },
];

window.fallers = [
  { x: 736, y: 404, size: 47, triggerX: 517 },
  { x: 1134, y: 512, size: 24, triggerX: 988 },
  { x: 3306, y: 631, size: 52, triggerX: 3102 },
  { x: 7687, y: 40, size: 45, triggerX: 7511 },
  { x: 8897, y: 197, size: 24, triggerX: 8762 },
  { x: 9787, y: 396, size: 24, triggerX: 9618 },
  { x: 17258, y: 169, size: 52, triggerX: 17058 },
  { x: 17689, y: 193, size: 29, triggerX: 17531 },
  { x: 21625, y: 598, size: 27, triggerX: 21476 },
];

window.switches = [
  { x: 5382, y: 447, radius: 26, gateId: "b10_g0" },
  { x: 19702, y: 642, radius: 26, gateId: "b10_g1" },
];

window.portals = [
  { id: "b10_p0a", x: 5101, y: 431, width: 40, height: 46, linkId: "b10_p0b" },
  { id: "b10_p0b", x: 10096, y: 485, width: 40, height: 46, linkId: "b10_p0a" },
];
