// Branch Level "Obsidian Rift" (id: b9) — see levels.js's
// TRUE_BRANCH_LEVELS and docs/gameplay.md's "Ten themed branch levels".
// Reachable only from its own Level Map node, never part of the
// sequential 1-100 path — see game.js's startBranchLevelFromOverlay()/
// completeBranchLevel(). Generated by .claude/gen-branch-levels.js;
// re-run audit-gaps.js/audit-checkpoints.js after regenerating.

window.levelText = "Obsidian Rift";
window.levelTheme = "obsidian";
window.levelBranchId = "b9";

window.platforms = [
  { x: 50, y: 380, width: 260, height: 20 },
  { x: 551, y: 431, width: 135, height: 26 },
  { x: 933, y: 508, width: 54, height: 19, moveAxis: "x", moveRange: 118, moveSpeed: 0.068, movePhase: 4.22 },
  { x: 1234, y: 615, width: 116, height: 16 },
  { x: 1597, y: 717, width: 218, height: 28, moveAxis: "x", moveRange: 117, moveSpeed: 0.049, movePhase: 3.5 },
  { x: 1974, y: 717, width: 264, height: 18 },
  { x: 2485, y: 793, width: 166, height: 26 },
  { x: 2892, y: 846, width: 195, height: 30 },
  { x: 3319, y: 881, width: 153, height: 25, bounce: true, bounceStrength: -21 },
  { x: 3694, y: 881, width: 104, height: 24, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 3957, y: 881, width: 231, height: 18 },
  { x: 4606, y: 819, width: 182, height: 28 },
  { x: 5187, y: 721, width: 52, height: 25, moveAxis: "y", moveRange: 163, moveSpeed: 0.053, movePhase: 2.57 },
  { x: 5632, y: 612, width: 187, height: 23 },
  { x: 6222, y: 518, width: 75, height: 27 },
  { x: 6456, y: 518, width: 348, height: 21 },
  { x: 6994, y: 449, width: 212, height: 14 },
  { x: 7396, y: 379, width: 97, height: 22, moveAxis: "y", moveRange: 100, moveSpeed: 0.071, movePhase: 1.99 },
  { x: 7924, y: 345, width: 111, height: 31, conveyor: true, conveyorSpeed: 1.91 },
  { x: 8194, y: 345, width: 234, height: 28 },
  { x: 8666, y: 388, width: 82, height: 30 },
  { x: 8995, y: 467, width: 94, height: 17 },
  { x: 9336, y: 547, width: 241, height: 18, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 9736, y: 547, width: 318, height: 27 },
  { x: 10301, y: 664, width: 105, height: 30 },
  { x: 10653, y: 759, width: 116, height: 27, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 11010, y: 820, width: 139, height: 20, conveyor: true, conveyorSpeed: 1.12 },
  { x: 11308, y: 820, width: 252, height: 18 },
  { x: 11788, y: 842, width: 83, height: 15 },
  { x: 12302, y: 811, width: 110, height: 20, moveAxis: "y", moveRange: 94, moveSpeed: 0.056, movePhase: 2.83 },
  { x: 12840, y: 775, width: 119, height: 29, melt: true, meltDelay: 18 },
  { x: 13368, y: 691, width: 246, height: 31 },
  { x: 14013, y: 586, width: 169, height: 15 },
  { x: 14341, y: 586, width: 240, height: 23 },
  { x: 14980, y: 482, width: 53, height: 20 },
  { x: 15208, y: 392, width: 158, height: 16 },
  { x: 15547, y: 310, width: 68, height: 23 },
  { x: 15809, y: 255, width: 235, height: 29 },
  { x: 16257, y: 233, width: 57, height: 23, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 16473, y: 233, width: 208, height: 29 },
  { x: 16928, y: 304, width: 228, height: 24 },
  { x: 17403, y: 386, width: 187, height: 27, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 17837, y: 497, width: 204, height: 15, bounce: true, bounceStrength: -21 },
  { x: 18226, y: 504, width: 415, height: 20 },
  { x: 4349, y: 852, width: 103, height: 16, gated: true, gateId: "b9_g0" },
];

window.deadlyPlatforms = [
  { x: 12362, y: 872, width: 68, height: 15, moveAxis: "x", moveRange: 78, moveSpeed: 0.06, movePhase: 2.04 },
  { x: 2678, y: 797, width: 125, height: 20 },
  { x: 5849, y: 617, width: 126, height: 20 },
  { x: 7227, y: 449, width: 123, height: 20 },
  { x: 11902, y: 841, width: 65, height: 20 },
  { x: 16078, y: 258, width: 119, height: 20 },
  { x: 17189, y: 311, width: 171, height: 20 },
];

window.spikes = [
  { x: 568, y: 431, size: 44 },
  { x: 612, y: 431, size: 50 },
  { x: 2545, y: 793, size: 51 },
  { x: 2596, y: 793, size: 12 },
  { x: 2920, y: 846, size: 48 },
  { x: 2968, y: 846, size: 14 },
  { x: 2982, y: 846, size: 12 },
  { x: 2994, y: 846, size: 22 },
  { x: 4642, y: 819, size: 41 },
  { x: 8678, y: 388, size: 38 },
  { x: 10339, y: 664, size: 45 },
  { x: 13423, y: 691, size: 28 },
  { x: 13451, y: 691, size: 37 },
  { x: 13488, y: 691, size: 32 },
  { x: 13520, y: 691, size: 24 },
  { x: 14053, y: 586, size: 58 },
  { x: 14111, y: 586, size: 21 },
  { x: 15260, y: 392, size: 47 },
  { x: 16986, y: 304, size: 17 },
  { x: 17003, y: 304, size: 58 },
];

window.checkpoints = [
  { x: 150, y: 350, reached: false },
  { x: 2106, y: 687, reached: false },
  { x: 4073, y: 851, reached: false },
  { x: 6630, y: 488, reached: false },
  { x: 8311, y: 315, reached: false },
  { x: 9895, y: 517, reached: false },
  { x: 11434, y: 790, reached: false },
  { x: 14461, y: 556, reached: false },
  { x: 16577, y: 203, reached: false },
  { x: 18434, y: 474, reached: false }, // Final
];

window.forceZones = [
  { x: 6462, y: 378, width: 336, height: 140, axis: "y", force: -0.157 },
];

window.lasers = [
  { x: 756, y: 363, length: 219, width: 4, baseAngle: 3.77, sweepAngle: 1.07, period: 136, blinkPeriod: 0, onRatio: 0.5 },
  { x: 1425, y: 558, length: 140, width: 4, baseAngle: 6.11, sweepAngle: 0, period: 136, blinkPeriod: 89, onRatio: 0.5 },
  { x: 2740, y: 722, length: 130, width: 4, baseAngle: 5.91, sweepAngle: 1.11, period: 136, blinkPeriod: 0, onRatio: 0.5 },
  { x: 3151, y: 794, length: 261, width: 4, baseAngle: 5.55, sweepAngle: 0, period: 136, blinkPeriod: 89, onRatio: 0.5 },
  { x: 3861, y: 811, length: 184, width: 4, baseAngle: 4.86, sweepAngle: 0.82, period: 136, blinkPeriod: 0, onRatio: 0.5 },
  { x: 4854, y: 777, length: 186, width: 4, baseAngle: 6.1, sweepAngle: 0, period: 136, blinkPeriod: 89, onRatio: 0.5 },
  { x: 5304, y: 627, length: 111, width: 4, baseAngle: 3.66, sweepAngle: 1.1, period: 136, blinkPeriod: 0, onRatio: 0.5 },
  { x: 7279, y: 373, length: 211, width: 4, baseAngle: 2.14, sweepAngle: 0.98, period: 136, blinkPeriod: 0, onRatio: 0.5 },
  { x: 8107, y: 302, length: 194, width: 4, baseAngle: 1.8, sweepAngle: 0.6, period: 136, blinkPeriod: 0, onRatio: 0.5 },
  { x: 10853, y: 682, length: 226, width: 4, baseAngle: 4.4, sweepAngle: 0, period: 136, blinkPeriod: 89, onRatio: 0.5 },
  { x: 11224, y: 757, length: 218, width: 4, baseAngle: 1.4, sweepAngle: 1.13, period: 136, blinkPeriod: 0, onRatio: 0.5 },
  { x: 13680, y: 604, length: 175, width: 4, baseAngle: 5.65, sweepAngle: 0, period: 136, blinkPeriod: 89, onRatio: 0.5 },
  { x: 14258, y: 497, length: 124, width: 4, baseAngle: 0.15, sweepAngle: 0.75, period: 136, blinkPeriod: 0, onRatio: 0.5 },
  { x: 15114, y: 439, length: 183, width: 4, baseAngle: 2.64, sweepAngle: 0, period: 136, blinkPeriod: 89, onRatio: 0.5 },
  { x: 16133, y: 169, length: 187, width: 4, baseAngle: 0.12, sweepAngle: 1, period: 136, blinkPeriod: 0, onRatio: 0.5 },
  { x: 16376, y: 184, length: 189, width: 4, baseAngle: 6.05, sweepAngle: 0, period: 136, blinkPeriod: 89, onRatio: 0.5 },
  { x: 17231, y: 209, length: 236, width: 4, baseAngle: 2.08, sweepAngle: 0, period: 136, blinkPeriod: 89, onRatio: 0.5 },
  { x: 18114, y: 412, length: 207, width: 4, baseAngle: 5.86, sweepAngle: 1.01, period: 136, blinkPeriod: 0, onRatio: 0.5 },
];

window.fallers = [
  { x: 1085, y: 387, size: 35, triggerX: 876 },
  { x: 5912, y: 503, size: 59, triggerX: 5725 },
  { x: 7573, y: 280, size: 25, triggerX: 7357 },
  { x: 10494, y: 554, size: 46, triggerX: 10322 },
  { x: 13015, y: 679, size: 57, triggerX: 12825 },
  { x: 15447, y: 289, size: 38, triggerX: 15248 },
];

window.switches = [
  { x: 4166, y: 851, radius: 26, gateId: "b9_g0" },
];
