// Branch Level "Toxic Hollow" (id: b3) — see levels.js's
// TRUE_BRANCH_LEVELS and docs/gameplay.md's "Ten themed branch levels".
// Reachable only from its own Level Map node, never part of the
// sequential 1-100 path — see game.js's startBranchLevelFromOverlay()/
// completeBranchLevel(). Generated by .claude/gen-branch-levels.js;
// re-run audit-gaps.js/audit-checkpoints.js after regenerating.

window.levelText = "Toxic Hollow";
window.levelTheme = "toxic";
window.levelBranchId = "b3";

window.platforms = [
  { x: 50, y: 380, width: 260, height: 20 },
  { x: 557, y: 462, width: 238, height: 23, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 1042, y: 555, width: 246, height: 16, moveAxis: "x", moveRange: 132, moveSpeed: 0.045, movePhase: 3.18 },
  { x: 1535, y: 639, width: 81, height: 31, moveAxis: "x", moveRange: 137, moveSpeed: 0.066, movePhase: 1.54 },
  { x: 1863, y: 746, width: 83, height: 20 },
  { x: 2105, y: 746, width: 367, height: 31 },
  { x: 2713, y: 808, width: 223, height: 30, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 3164, y: 829, width: 108, height: 29 },
  { x: 3494, y: 832, width: 62, height: 22, conveyor: true, conveyorSpeed: -1.83 },
  { x: 3715, y: 832, width: 254, height: 27 },
  { x: 4397, y: 792, width: 178, height: 18, melt: true, meltDelay: 18 },
  { x: 4978, y: 704, width: 144, height: 22 },
  { x: 5287, y: 603, width: 95, height: 29 },
  { x: 5557, y: 511, width: 221, height: 21, moveAxis: "x", moveRange: 110, moveSpeed: 0.063, movePhase: 2.38 },
  { x: 5937, y: 511, width: 303, height: 18 },
  { x: 6643, y: 417, width: 68, height: 16, melt: true, meltDelay: 18 },
  { x: 6911, y: 369, width: 228, height: 20 },
  { x: 7348, y: 343, width: 155, height: 28 },
  { x: 7725, y: 343, width: 163, height: 29 },
  { x: 8047, y: 343, width: 337, height: 17 },
  { x: 8625, y: 406, width: 185, height: 27, melt: true, meltDelay: 18 },
  { x: 9057, y: 473, width: 73, height: 16, melt: true, meltDelay: 18 },
  { x: 9377, y: 576, width: 67, height: 18, moveAxis: "x", moveRange: 109, moveSpeed: 0.055, movePhase: 3.99 },
  { x: 9691, y: 687, width: 131, height: 17 },
  { x: 9981, y: 687, width: 255, height: 19 },
  { x: 10483, y: 752, width: 156, height: 23 },
  { x: 10880, y: 808, width: 177, height: 16 },
  { x: 11289, y: 843, width: 209, height: 18, moveAxis: "x", moveRange: 121, moveSpeed: 0.059, movePhase: 2.21 },
  { x: 11717, y: 834, width: 152, height: 21 },
  { x: 12028, y: 834, width: 385, height: 26 },
  { x: 12597, y: 758, width: 133, height: 16 },
  { x: 12914, y: 686, width: 144, height: 28, moveAxis: "y", moveRange: 116, moveSpeed: 0.065, movePhase: 4 },
  { x: 13461, y: 591, width: 143, height: 27 },
  { x: 13785, y: 508, width: 101, height: 25 },
  { x: 14045, y: 508, width: 272, height: 26 },
  { x: 14729, y: 441, width: 58, height: 25, moveAxis: "x", moveRange: 112, moveSpeed: 0.062, movePhase: 2.61 },
  { x: 14990, y: 407, width: 219, height: 24 },
  { x: 15640, y: 383, width: 108, height: 17, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 15980, y: 411, width: 165, height: 29 },
  { x: 16304, y: 411, width: 405, height: 24 },
  { x: 16950, y: 471, width: 64, height: 31 },
  { x: 17261, y: 577, width: 167, height: 26 },
  { x: 17614, y: 588, width: 435, height: 20 },
  { x: 6415, y: 475, width: 114, height: 16, gated: true, gateId: "b3_g0" },
];

window.deadlyPlatforms = [
  { x: 1136, y: 602, width: 178, height: 18, moveAxis: "y", moveRange: 118, moveSpeed: 0.042, movePhase: 6.15 },
  { x: 5640, y: 551, width: 140, height: 18, moveAxis: "y", moveRange: 106, moveSpeed: 0.078, movePhase: 1.7 },
  { x: 11247, y: 887, width: 165, height: 20, moveAxis: "y", moveRange: 127, moveSpeed: 0.071, movePhase: 5.57 },
  { x: 5144, y: 697, width: 82, height: 20 },
  { x: 7173, y: 369, width: 141, height: 20 },
  { x: 7920, y: 338, width: 130, height: 20 },
  { x: 9857, y: 679, width: 97, height: 20 },
  { x: 10661, y: 751, width: 85, height: 20 },
  { x: 11080, y: 808, width: 90, height: 20 },
  { x: 13910, y: 505, width: 69, height: 20 },
  { x: 15239, y: 416, width: 175, height: 20 },
  { x: 16182, y: 411, width: 97, height: 20 },
  { x: 17453, y: 573, width: 131, height: 20 },
];

window.spikes = [
  { x: 3197, y: 829, size: 44 },
  { x: 4998, y: 704, size: 23 },
  { x: 5305, y: 603, size: 34 },
  { x: 7384, y: 343, size: 45 },
  { x: 12615, y: 758, size: 20 },
  { x: 13481, y: 591, size: 30 },
  { x: 13511, y: 591, size: 54 },
  { x: 13816, y: 508, size: 26 },
];

window.checkpoints = [
  { x: 150, y: 350, reached: false },
  { x: 2289, y: 716, reached: false },
  { x: 3842, y: 802, reached: false },
  { x: 6089, y: 481, reached: false },
  { x: 8216, y: 313, reached: false },
  { x: 10109, y: 657, reached: false },
  { x: 12221, y: 804, reached: false },
  { x: 14181, y: 478, reached: false },
  { x: 16507, y: 381, reached: false },
  { x: 17832, y: 558, reached: false }, // Final
];

window.forceZones = [
  { x: 16310, y: 271, width: 393, height: 140, axis: "y", force: 0.127 },
];

window.lasers = [
  { x: 851, y: 408, length: 265, width: 4, baseAngle: 0.44, sweepAngle: 0, period: 144, blinkPeriod: 96, onRatio: 0.5 },
  { x: 1370, y: 500, length: 183, width: 4, baseAngle: 6.17, sweepAngle: 0.56, period: 144, blinkPeriod: 0, onRatio: 0.5 },
  { x: 3027, y: 718, length: 121, width: 4, baseAngle: 1.81, sweepAngle: 1.09, period: 144, blinkPeriod: 0, onRatio: 0.5 },
  { x: 3327, y: 735, length: 153, width: 4, baseAngle: 4.81, sweepAngle: 0, period: 144, blinkPeriod: 96, onRatio: 0.5 },
  { x: 4657, y: 732, length: 183, width: 4, baseAngle: 6.09, sweepAngle: 0.68, period: 144, blinkPeriod: 0, onRatio: 0.5 },
  { x: 7590, y: 283, length: 235, width: 4, baseAngle: 4.63, sweepAngle: 0, period: 144, blinkPeriod: 96, onRatio: 0.5 },
  { x: 7943, y: 265, length: 221, width: 4, baseAngle: 0.31, sweepAngle: 0.7, period: 144, blinkPeriod: 0, onRatio: 0.5 },
  { x: 9536, y: 467, length: 118, width: 4, baseAngle: 4.38, sweepAngle: 1.07, period: 144, blinkPeriod: 0, onRatio: 0.5 },
  { x: 11145, y: 753, length: 149, width: 4, baseAngle: 4.33, sweepAngle: 0.61, period: 144, blinkPeriod: 0, onRatio: 0.5 },
  { x: 11585, y: 760, length: 130, width: 4, baseAngle: 3.02, sweepAngle: 1.12, period: 144, blinkPeriod: 0, onRatio: 0.5 },
  { x: 13696, y: 528, length: 218, width: 4, baseAngle: 5.65, sweepAngle: 0.63, period: 144, blinkPeriod: 0, onRatio: 0.5 },
];

window.fallers = [
  { x: 5456, y: 454, size: 49, triggerX: 5303 },
  { x: 6767, y: 295, size: 37, triggerX: 6563 },
  { x: 12786, y: 618, size: 41, triggerX: 12609 },
  { x: 15268, y: 272, size: 29, triggerX: 15049 },
];

window.switches = [
  { x: 6218, y: 481, radius: 26, gateId: "b3_g0" },
];
