// Branch Level "Glacier Spire" (id: b2) — see levels.js's
// TRUE_BRANCH_LEVELS and docs/gameplay.md's "Ten themed branch levels".
// Reachable only from its own Level Map node, never part of the
// sequential 1-100 path — see game.js's startBranchLevelFromOverlay()/
// completeBranchLevel(). Generated by .claude/gen-branch-levels.js;
// re-run audit-gaps.js/audit-checkpoints.js after regenerating.

window.levelText = "Glacier Spire";
window.levelTheme = "glacier";
window.levelBranchId = "b2";

window.platforms = [
  { x: 50, y: 380, width: 260, height: 20 },
  { x: 747, y: 363, width: 128, height: 22, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 1103, y: 383, width: 226, height: 15, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 1567, y: 430, width: 214, height: 19, bounce: true, bounceStrength: -17 },
  { x: 2028, y: 509, width: 128, height: 14, moveAxis: "x", moveRange: 136, moveSpeed: 0.045, movePhase: 2.05 },
  { x: 2315, y: 509, width: 325, height: 22 },
  { x: 2887, y: 616, width: 149, height: 18, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 3283, y: 715, width: 155, height: 22 },
  { x: 3685, y: 806, width: 195, height: 24 },
  { x: 4121, y: 869, width: 159, height: 29, bounce: true, bounceStrength: -19 },
  { x: 4518, y: 909, width: 168, height: 22, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 4845, y: 909, width: 213, height: 31 },
  { x: 5499, y: 901, width: 71, height: 17 },
  { x: 5992, y: 846, width: 219, height: 31, moveAxis: "y", moveRange: 109, moveSpeed: 0.05, movePhase: 5.05 },
  { x: 6629, y: 787, width: 73, height: 28, moveAxis: "x", moveRange: 103, moveSpeed: 0.065, movePhase: 1.27 },
  { x: 7111, y: 705, width: 233, height: 25 },
  { x: 7503, y: 705, width: 330, height: 25 },
  { x: 7995, y: 596, width: 240, height: 26 },
  { x: 8410, y: 508, width: 160, height: 31 },
  { x: 8988, y: 446, width: 91, height: 24 },
  { x: 9282, y: 408, width: 50, height: 29, bounce: true, bounceStrength: -17 },
  { x: 9491, y: 408, width: 280, height: 25 },
  { x: 9999, y: 429, width: 56, height: 22, moveAxis: "y", moveRange: 123, moveSpeed: 0.041, movePhase: 1.76 },
  { x: 10302, y: 498, width: 225, height: 14 },
  { x: 10774, y: 579, width: 75, height: 15, moveAxis: "x", moveRange: 121, moveSpeed: 0.055, movePhase: 4.86 },
  { x: 11096, y: 683, width: 152, height: 27, moveAxis: "x", moveRange: 104, moveSpeed: 0.05, movePhase: 5.34 },
  { x: 11495, y: 766, width: 152, height: 16, ghost: true, ghostPeriod: 120, ghostOnRatio: 0.4 },
  { x: 11806, y: 766, width: 383, height: 30 },
  { x: 12436, y: 846, width: 94, height: 17, melt: true, meltDelay: 18 },
  { x: 12771, y: 899, width: 53, height: 30 },
  { x: 13052, y: 919, width: 189, height: 22, bounce: true, bounceStrength: -20 },
  { x: 13463, y: 920, width: 127, height: 20 },
  { x: 13790, y: 875, width: 162, height: 23 },
  { x: 14111, y: 875, width: 239, height: 31 },
  { x: 14759, y: 793, width: 58, height: 23 },
  { x: 14998, y: 713, width: 247, height: 25, melt: true, meltDelay: 18 },
  { x: 15426, y: 630, width: 243, height: 25, conveyor: true, conveyorSpeed: 1.26 },
  { x: 15850, y: 549, width: 215, height: 23 },
  { x: 16474, y: 472, width: 58, height: 25, melt: true, meltDelay: 18 },
  { x: 16691, y: 472, width: 381, height: 19 },
  { x: 17503, y: 446, width: 246, height: 15, moveAxis: "x", moveRange: 119, moveSpeed: 0.065, movePhase: 6.19 },
  { x: 17981, y: 474, width: 162, height: 18, moveAxis: "x", moveRange: 151, moveSpeed: 0.045, movePhase: 4.72 },
  { x: 18375, y: 504, width: 101, height: 30 },
  { x: 18685, y: 496, width: 434, height: 20 },
  { x: 2815, y: 465, width: 103, height: 16, gated: true, gateId: "b2_g0" },
];

window.deadlyPlatforms = [
  { x: 11137, y: 738, width: 125, height: 23, moveAxis: "y", moveRange: 113, moveSpeed: 0.055, movePhase: 3.11 },
  { x: 17428, y: 473, width: 185, height: 20, moveAxis: "y", moveRange: 91, moveSpeed: 0.061, movePhase: 0.18 },
  { x: 3910, y: 801, width: 100, height: 20 },
  { x: 8607, y: 509, width: 107, height: 20 },
  { x: 13613, y: 927, width: 114, height: 20 },
];

window.spikes = [
  { x: 3332, y: 715, size: 35 },
  { x: 3367, y: 715, size: 44 },
  { x: 3736, y: 806, size: 25 },
  { x: 8450, y: 508, size: 47 },
  { x: 9008, y: 446, size: 57 },
  { x: 10346, y: 498, size: 12 },
  { x: 12784, y: 899, size: 14 },
  { x: 18398, y: 504, size: 31 },
];

window.checkpoints = [
  { x: 150, y: 350, reached: false },
  { x: 2478, y: 479, reached: false },
  { x: 4952, y: 879, reached: false },
  { x: 7668, y: 675, reached: false },
  { x: 9631, y: 378, reached: false },
  { x: 11998, y: 736, reached: false },
  { x: 14231, y: 845, reached: false },
  { x: 16882, y: 442, reached: false },
  { x: 18902, y: 466, reached: false }, // Final
];

window.forceZones = [
  { x: 7513, y: 615, width: 310, height: 90, axis: "x", force: 0.162 },
  { x: 14117, y: 735, width: 227, height: 140, axis: "y", force: -0.215 },
];

window.lasers = [
  { x: 5638, y: 824, length: 133, width: 4, baseAngle: 3.56, sweepAngle: 0, period: 147, blinkPeriod: 98, onRatio: 0.5 },
  { x: 8295, y: 539, length: 249, width: 4, baseAngle: 0.03, sweepAngle: 0.69, period: 147, blinkPeriod: 0, onRatio: 0.5 },
  { x: 9399, y: 358, length: 259, width: 4, baseAngle: 0.12, sweepAngle: 0.78, period: 147, blinkPeriod: 0, onRatio: 0.5 },
  { x: 10601, y: 453, length: 173, width: 4, baseAngle: 0.66, sweepAngle: 0, period: 147, blinkPeriod: 98, onRatio: 0.5 },
  { x: 14009, y: 807, length: 127, width: 4, baseAngle: 4.32, sweepAngle: 0, period: 147, blinkPeriod: 98, onRatio: 0.5 },
];

window.fallers = [
  { x: 1408, y: 300, size: 47, triggerX: 1189 },
  { x: 1852, y: 282, size: 42, triggerX: 1666 },
  { x: 3518, y: 591, size: 32, triggerX: 3317 },
  { x: 3970, y: 680, size: 28, triggerX: 3769 },
  { x: 4756, y: 777, size: 50, triggerX: 4545 },
  { x: 12609, y: 710, size: 56, triggerX: 12446 },
  { x: 15310, y: 608, size: 54, triggerX: 15123 },
  { x: 18561, y: 393, size: 33, triggerX: 18378 },
];

window.switches = [
  { x: 2618, y: 479, radius: 26, gateId: "b2_g0" },
];
