// Generates levelN.js files using the exact same physics game.js and the
// safety audits (audit-*.js in this directory) use, so every gap is
// verified feasible (or deliberately gated by a ghost platform, like
// level 3) at generation time instead of hand-placed and hoped safe.
//
// Usage: node .claude/gen-levels.js [outDir] [fromLevel] [toLevel]
//   outDir defaults to the project root; fromLevel/toLevel default to 26/100.
//   (levels 1-25 were generated by an earlier version of this script and
//   are hand/ramp-tuned separately — see git history if they ever need
//   regenerating; this version's difficulty tiers, below, are calibrated
//   to continue on from where those left off, not to reproduce them.)
// After running, always re-run audit-gaps.js and audit-checkpoints.js —
// this script validates gaps and checkpoints it places directly, but
// doesn't replace those as the source of truth for the whole level set.
//
// Difficulty is organized into named TIERS (see TIERS below) rather than a
// single ramp across every generated level:
//   - Levels 26-75 continue the original 1-25 escalation (a new "chapter"
//     rather than a reset — see BLOCK_A's floorT starting above 0, not at
//     0) up through a noticeably harder ceiling by 75.
//   - Levels 76-100 are a deliberately harder final stretch: taller,
//     mostly-upward "vertical" climbs (see the climbBias math in
//     placeStep()) rather than the oscillating rollercoaster shape earlier
//     levels use, sparser checkpoints (so more of each climb has to be
//     cleared in one go — still perfectly safe once reached, just harder
//     to reach; see harderCheckpoints), and more mandatory ghost gates.
// A handful of levels in both tiers are BONUS levels (see BONUS_LEVELS) —
// named destinations rather than another numbered rung on the ladder, each
// built around one mechanic turned up far past its normal share (heavy
// conveyor use, heavy crisscrossing red decoys, a pure vertical climb, a
// finale gauntlet combining everything) or, for "The Neon Rift," a
// wholesale visual reskin (`window.levelTheme`, see game.js's
// drawBackground()/drawInsetRect()) instead of the normal nebula backdrop.
//
// New mechanics beyond the original moving/ghost/melt set (see
// docs/gameplay.md for the full writeup once added):
//   - `bounce: true` platforms launch the player hard on landing
//     (BOUNCE_STRENGTH in game.js) — always an optional faster/higher
//     route, never load-bearing for a gap's base feasibility, so it can't
//     turn a verified-safe jump into a hope-it-works one.
//   - `conveyor: true` + `conveyorSpeed` platforms push the player
//     horizontally while they stand on it.
//   - Deadly platforms can now move too (`moveAxis`/`moveRange`/etc, same
//     fields as a moving solid platform — see game.js's updateMoverList())
//     — used here to spawn a red "twin" alongside some moving solid
//     platforms, oscillating on the opposite axis so their paths visibly
//     cross, the obvious "which one is safe?" trick.
const fs = require("fs");
const path = require("path");

const gravity = 0.5;
const jumpStrength = -12;
const horizontalSpeed = 5;

function simulate(secondJumpFrame) {
  let y = 0, dy = jumpStrength, x = 0;
  let doubleUsed = false;
  const pts = [{ x, y }];
  for (let frame = 0; frame < 250; frame++) {
    dy += gravity;
    x += horizontalSpeed;
    y += dy;
    if (secondJumpFrame != null && frame === secondJumpFrame && !doubleUsed) {
      dy = jumpStrength;
      doubleUsed = true;
    }
    pts.push({ x, y });
  }
  return pts;
}
const singlePath = simulate(null);
const doublePaths = [];
for (let t = 0; t <= 45; t++) doublePaths.push(simulate(t));

function canClearPath(pts, dx, rise) {
  for (const p of pts) {
    if (p.x >= dx) return -p.y >= rise;
  }
  return false;
}
const canSingle = (dx, rise) => canClearPath(singlePath, dx, rise);
const canDouble = (dx, rise) => doublePaths.some((p) => canClearPath(p, dx, rise));

// The largest dx that's still feasible for a given rise — used to place
// gaps a controlled fraction of the way to "actually impossible" instead
// of comfortably inside it, so difficulty can scale how much margin for
// error a jump leaves (see marginFactor in placeStep()) rather than every
// gap having the same generous slack regardless of level.
function maxSingleDx(rise, searchCeiling = 260) {
  let dx = searchCeiling;
  while (dx > 20 && !canSingle(dx, rise)) dx -= 2;
  return dx;
}
function maxDoubleDx(rise, searchCeiling = 500) {
  let dx = searchCeiling;
  while (dx > 20 && !canDouble(dx, rise)) dx -= 2;
  return dx;
}

// Deterministic PRNG (mulberry32) so re-runs are reproducible.
function mulberry32(seed) {
  let a = seed;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Flavor names for levels 26-100 (for the level-select map — see
// levels.js's own copy of this same list — and, for BONUS_LEVELS below,
// for the in-game levelText too). Levels 1-25's names live only in
// levels.js/docs/gameplay.md now; this earlier version's own 13-25 map is
// gone since this script no longer regenerates that range (see header).
const NEW_LEVEL_NAMES = {
  26: "Comet's Wake", 27: "Fractured Skyline", 28: "The Drifting Vault", 29: "Ashen Causeway",
  30: "Hollow Meridian", 31: "The Silent Reach", 32: "Ember Threshold", 33: "Wraithlight Span",
  34: "The Cinder Steps", 35: "Skyline Interlude", 36: "Obsidian Furrow", 37: "The Widening Dark",
  38: "Starcross Gauntlet", 39: "Molten Parapet", 40: "The Hush Between", 41: "Ravenfall Reach",
  42: "The Splintered Vault", 43: "Duskbound Causeway", 44: "The Umbral Stair", 45: "Cindermarch",
  46: "The Glass Divide", 47: "Starless Culvert", 48: "The Withering Span", 49: "Ashen Zenith",
  50: "The Neon Rift", 51: "The Fractured Choir", 52: "Voidlight Traverse", 53: "The Ember Maze",
  54: "Graven Skyway", 55: "The Hollow Ascent", 56: "Starwake Perimeter", 57: "The Splitting Dark",
  58: "Cinderfall Vault", 59: "The Widow's Ledge", 60: "Umbral Gauntlet", 61: "The Drowned Sky",
  62: "Ashfall Perimeter", 63: "The Ember Choir", 64: "Nightglass Span", 65: "Crossfire Causeway",
  66: "The Faultline Reach", 67: "Starbound Furrow", 68: "The Whispering Vault", 69: "Molten Meridian",
  70: "The Cracked Horizon", 71: "Ravenous Span", 72: "The Deep Cinder", 73: "Starfall Reprise",
  74: "The Last Ember", 75: "Starshade's Ascension",
  76: "The Vertical Ledge", 77: "Skybreak Chasm", 78: "The Climbing Dark", 79: "Cindertower Reach",
  80: "The Wraith Stair", 81: "Ashen Spire", 82: "The Vertical Vein", 83: "The Fracturing Sky",
  84: "Starwell Descent", 85: "The Molten Stair", 86: "Umbral Spire", 87: "The Hollow Zenith",
  88: "Starcross Spire", 89: "The Widening Vault", 90: "Cinderspire Reach", 91: "The Faultline Ascent",
  92: "Nightglass Spire", 93: "The Drowned Zenith", 94: "Starfall Spire", 95: "Mirror's End",
  96: "The Final Cinder", 97: "Starshade's Trial", 98: "The Last Ascent", 99: "The Abyssal Spire",
  100: "Starshade's Eternity",
};

// Named "branch" levels — a handful of levels built around one mechanic
// turned up far past its normal share (or, for the Neon Rift, a wholesale
// visual reskin) rather than another rung on the ladder. levels.js renders
// these as a spur off the main path on the level map, using this same set
// of level numbers, so the two files must stay in sync.
const BONUS_LEVELS = {
  35: { mechanicFocus: "conveyor" },
  50: { mechanicFocus: "neon", theme: "neon" },
  65: { mechanicFocus: "crisscross" },
  82: { mechanicFocus: "vertical" },
  95: { mechanicFocus: "gauntlet" },
};

// Levels 26-75 continue the original escalation as a new chapter (starting
// above t=0, not resetting to it); 76-100 are a deliberately harder final
// stretch with mostly-upward "vertical" climbs and sparser checkpoints
// (see placeStep()'s climbBias and the breather-interval check below).
const BLOCK_A = { start: 26, end: 75, floorT: 0.85, ceilT: 1.35, vertical: false, harderCheckpoints: false };
const BLOCK_B = { start: 76, end: 100, floorT: 1.3, ceilT: 1.9, vertical: true, harderCheckpoints: true };
function tierForLevel(n) {
  return n <= 75 ? BLOCK_A : BLOCK_B;
}

// Resolves every difficulty knob for level `n` up front — the tier's base
// interpolation, then a bonus level's mechanic-focus overrides on top, if
// any — so generateLevel() itself just reads `params.x` rather than
// re-deriving any of this.
function resolveParams(n) {
  const tier = tierForLevel(n);
  const raw = tier.end > tier.start ? (n - tier.start) / (tier.end - tier.start) : 0;
  const t = tier.floorT + raw * (tier.ceilT - tier.floorT);
  const bonus = BONUS_LEVELS[n] || null;
  const cap = (v, max) => Math.min(max, v);
  const tCapped = Math.min(t, 1.5);

  const params = {
    n,
    t,
    vertical: tier.vertical,
    harderCheckpoints: tier.harderCheckpoints,
    spikeChance: cap(0.4 + 0.4 * t, 0.92),
    movableChance: cap(0.45 + 0.35 * t, 0.92),
    ghostShare: cap(0.35 + 0.15 * t, 0.55), // share of "movable" slots that become ghost instead of moving
    meltShare: cap(0.2 + 0.12 * t, 0.34),
    bounceShare: cap(0.05 + 0.12 * tCapped, 0.24),
    conveyorShare: cap(0.04 + 0.1 * tCapped, 0.2),
    decoyChance: cap(0.28 + 0.4 * t, 0.85),
    crisscrossChance: cap(0.12 + 0.3 * tCapped, 0.6),
    moveSpeedBase: Math.min(0.075, 0.022 + 0.022 * t),
    moveRangeBase: Math.min(170, 50 + 45 * t),
    numSteps: tier.vertical
      ? 22 + Math.round(14 * Math.min(t, 1.3))
      : 18 + Math.round(10 * Math.min(t, 1.35)),
    // Mandatory ghost gates (a gap too wide for even a double jump, like
    // level 3's — see the sanity checks below) only start appearing in the
    // harder half of each tier, and the vertical tier allows one more.
    mandatoryGhostGates: tier.vertical
      ? (t < 1.4 ? 1 : t < 1.7 ? 2 : 3)
      : (t < 1.0 ? 0 : t < 1.2 ? 1 : 2),
    theme: bonus && bonus.theme ? bonus.theme : null,
    name: NEW_LEVEL_NAMES[n] || `Level ${n}`,
    isBonus: !!bonus,
  };

  if (bonus) {
    if (bonus.mechanicFocus === "conveyor") {
      params.conveyorShare = 0.6;
      params.bounceShare = 0.05;
      params.crisscrossChance = 0.15;
      params.movableChance = cap(params.movableChance + 0.1, 0.95);
      params.t = Math.min(params.t, 1.05); // a brisk, fun interlude, not a brutal spike
    } else if (bonus.mechanicFocus === "neon") {
      params.bounceShare = 0.35;
      params.conveyorShare = 0.15;
      params.crisscrossChance = 0.25;
      params.t = Math.min(params.t, 0.95); // a showpiece, not the hardest level around it
    } else if (bonus.mechanicFocus === "crisscross") {
      params.crisscrossChance = 0.85;
      params.decoyChance = cap(params.decoyChance + 0.15, 0.9);
      params.movableChance = cap(params.movableChance + 0.1, 0.95);
    } else if (bonus.mechanicFocus === "vertical") {
      params.vertical = true;
      params.harderCheckpoints = true;
      params.bounceShare = 0.3;
      params.numSteps += 8;
      params.mandatoryGhostGates = Math.max(params.mandatoryGhostGates, 2);
    } else if (bonus.mechanicFocus === "gauntlet") {
      params.crisscrossChance = 0.6;
      params.bounceShare = 0.2;
      params.conveyorShare = 0.15;
      params.harderCheckpoints = true;
      params.mandatoryGhostGates = Math.max(params.mandatoryGhostGates, 2);
      params.t = Math.max(params.t, tier.ceilT * 0.95);
    }
  }

  // ghostShare/meltShare/bounceShare/conveyorShare are each independent
  // "share of the movable pool" values, and at this tier ceiling (t can
  // reach ~1.9) or under a bonus level's override they can add up past 1
  // on their own — which would starve out plain moving platforms almost
  // entirely (subRoll, drawn uniformly from [0,1), would practically never
  // land past all four cumulative cuts). Plain movers are load-bearing for
  // the crisscrossing-decoy mechanic (Pass 3 in generateLevel() only
  // attaches a red twin to a platform that actually has `moveAxis`), so
  // every level keeps at least ~18% of its movable pool as ordinary
  // movers, scaling the other four down proportionally rather than letting
  // any one type crowd the rest out entirely.
  const shareTotal = params.ghostShare + params.meltShare + params.bounceShare + params.conveyorShare;
  const maxShareTotal = 0.82;
  if (shareTotal > maxShareTotal) {
    const scale = maxShareTotal / shareTotal;
    params.ghostShare *= scale;
    params.meltShare *= scale;
    params.bounceShare *= scale;
    params.conveyorShare *= scale;
  }

  return params;
}

function generateLevel(n) {
  const params = resolveParams(n);
  const rand = mulberry32(n * 97531 + 7);
  // Probability knobs already have their own caps (see resolveParams()) —
  // this local, separately-clamped `t` is only for the cosmetic magnitude
  // formulas below (spike size, ghost timing, jump-margin tightness) so a
  // very high tier ceiling can't blow those out to absurd values.
  const t = Math.min(params.t, 1.4);

  const spikeChance = params.spikeChance;
  const movableChance = params.movableChance;
  const ghostShare = params.ghostShare;
  const meltShare = params.meltShare;
  const bounceShare = params.bounceShare;
  const conveyorShare = params.conveyorShare;
  const decoyChance = params.decoyChance;
  const crisscrossChance = params.crisscrossChance;
  const moveSpeedBase = params.moveSpeedBase;
  const moveRangeBase = params.moveRangeBase;
  const numSteps = params.numSteps;
  const mandatoryGhostGates = params.mandatoryGhostGates;
  const vertical = params.vertical;
  const harderCheckpoints = params.harderCheckpoints;

  const platforms = [];
  const deadlyPlatforms = [];
  const spikes = [];
  const checkpoints = [];

  let x = 50;
  let y = 380; // nominal, runtime centering handles the real viewport
  const startWidth = 250;
  platforms.push({ x, y, width: startWidth, height: 20 });
  checkpoints.push({ x: x + 100, y: y - 30, reached: false });

  let sinceBreather = 0;
  let ghostGatesPlaced = 0;
  let curX = x + startWidth;
  let curY = y;
  const candidateIndices = []; // indices into `platforms` eligible to become moving/ghost/melt

  function placeStep(riseTarget, wide) {
    // Pick a dx that keeps this gap within single-jump range for the
    // target rise; occasionally (climbing hard) fall back to a
    // double-jump-only distance instead, matching the existing levels'
    // "needs a double jump (ok if intentional)" design language. How
    // close dx sits to the actual feasibility boundary (vs. comfortably
    // inside it) scales with difficulty — marginFactor near 1 means the
    // jump is timed right up against what's physically still possible,
    // leaving very little room for a mistimed press; breathers (`wide`)
    // are deliberately exempt, since a level needs *some* stretches where
    // the player can actually breathe rather than every single gap being
    // maximally tight.
    const marginFactor = wide ? 0.7 : Math.min(0.97, 0.74 + 0.22 * t); // 0.74 -> 0.97 over the ramp
    const wantsDouble = rand() < 0.22 + 0.25 * t && riseTarget > 0;
    let dx;
    if (wantsDouble && canDouble(320, riseTarget)) {
      const maxDx = maxDoubleDx(riseTarget);
      dx = Math.max(180, Math.round(maxDx * marginFactor));
      while (dx > 180 && !canDouble(dx, riseTarget)) dx -= 5;
    } else {
      const maxDx = maxSingleDx(riseTarget);
      dx = Math.max(60, Math.round(maxDx * marginFactor));
      while (dx > 60 && !canSingle(dx, riseTarget)) dx -= 5;
    }
    // Width and thickness both vary more than the hand-authored levels
    // ever did — a real platformer's boxes aren't all the same stamped
    // 20px-thick slab. Thickness never matters for feasibility (only the
    // top surface y does — see resolveAxis() in game.js), so it's free to
    // vary purely for visual/difficulty texture — but kept in a
    // proportionate range (14-30px, vs. the player's 25px) rather than
    // the wider 12-46px this originally shipped with, which let a narrow
    // platform roll a height close to its own width and read as a bulky
    // square block instead of a platform.
    const width = wide
      ? 180 + Math.floor(rand() * 220)
      : 45 + Math.floor(rand() * 190);
    const height = 14 + Math.floor(rand() * 17);
    const px = curX + dx;
    const py = curY - riseTarget;
    curX = px + width; // track the RIGHT edge — the next gap is measured from here
    curY = py;
    return { x: px, y: py, width, height };
  }

  for (let i = 0; i < numSteps; i++) {
    sinceBreather++;
    // The "harder to reach checkpoints" tiers space breathers (and
    // therefore checkpoints) further apart — more consecutive hard jumps
    // between safe rests — without touching how safe landing on one
    // actually is once you get there (still fully audited below).
    const isBreather = harderCheckpoints
      ? sinceBreather >= 6 + Math.floor(rand() * 3)
      : sinceBreather >= 4 + Math.floor(rand() * 2);
    // Ordinary levels oscillate climb/dip, like levels 6/9's rollercoaster
    // shape, so the level has visual rhythm instead of monotonically
    // climbing off the visible band forever. "Vertical" levels (76-100 —
    // see BLOCK_B/tierForLevel()) instead add a steady upward climbBias on
    // top of a smaller oscillation, so most steps climb and only
    // occasionally dip — a real staircase into the sky rather than a
    // rollercoaster, made possible now that the camera scrolls vertically
    // without limit (see docs/gameplay.md).
    const phase = Math.sin(i / 3.2 + n);
    const oscAmplitude = vertical ? 25 + 20 * t : 40 + 50 * t;
    const climbBias = vertical ? 16 + 20 * Math.min(params.t, 1.6) : 0;
    const riseTarget = Math.round(phase * oscAmplitude + (rand() - 0.5) * 30 + climbBias);

    // Occasionally gate a gap behind a mandatory ghost platform (like
    // level 3) — only in the harder back half of the new levels, and only
    // a couple of times per level.
    if (
      ghostGatesPlaced < mandatoryGhostGates &&
      isBreather &&
      rand() < 0.5 &&
      i > 4 &&
      i < numSteps - 4
    ) {
      const preGap = { x: curX, y: curY, width: 240 + Math.floor(rand() * 60), height: 20 };
      platforms.push(preGap);
      curX = preGap.x + preGap.width;
      curY = preGap.y;

      const bridgeY = curY - (10 + Math.floor(rand() * 20));
      const bridgeX = curX + 190 + Math.floor(rand() * 20);
      platforms.push({
        x: bridgeX,
        y: bridgeY,
        width: 90 + Math.floor(rand() * 20),
        ghost: true,
        height: 20,
        ghostPeriod: Math.max(120, 190 - Math.round(70 * t)),
        ghostOnRatio: Math.max(0.35, 0.6 - 0.2 * t),
      });
      const bridgeEnd = bridgeX + 90;

      const postRise = 10 + Math.floor(rand() * 20);
      const postX = bridgeEnd + 190 + Math.floor(rand() * 20);
      const postY = bridgeY - postRise;
      const postPlatform = { x: postX, y: postY, width: 220 + Math.floor(rand() * 60), height: 20 };
      platforms.push(postPlatform);
      curX = postPlatform.x + postPlatform.width;
      curY = postPlatform.y;

      // Sanity: the direct pre->post distance must genuinely exceed a
      // double jump's reach, and each half must be a comfortable single
      // jump, or this generator has a bug.
      const directDx = postPlatform.x - preGap.x - preGap.width;
      const directRise = preGap.y - postPlatform.y;
      if (canDouble(directDx, directRise)) {
        throw new Error(`Level ${n}: ghost gate not actually mandatory (direct dx=${directDx} rise=${directRise})`);
      }
      const hop1Dx = bridgeX - (preGap.x + preGap.width);
      const hop1Rise = preGap.y - bridgeY;
      const hop2Dx = postX - bridgeEnd;
      const hop2Rise = bridgeY - postY;
      if (!canSingle(hop1Dx, hop1Rise) || !canSingle(hop2Dx, hop2Rise)) {
        throw new Error(`Level ${n}: ghost gate sub-hop not single-jump safe`);
      }

      ghostGatesPlaced++;
      checkpoints.push({ x: postPlatform.x + 60, y: postPlatform.y - 30, reached: false });
      sinceBreather = 0;
      continue;
    }

    // Every step is generated as a plain solid platform first — whether it
    // becomes a moving/ghost/melt platform is decided in a second pass
    // below, once every position is finalized and neighbors are known.
    // (An earlier version decided this up front, per-step; that let an
    // incidental ghost/melt platform silently turn the gap around it into
    // an unvalidated, accidental "mandatory gate" — the very thing the
    // explicit gate mechanic above exists to do safely.)
    const step = placeStep(isBreather ? 0 : riseTarget, isBreather);
    platforms.push(step);

    if (!isBreather) candidateIndices.push(platforms.length - 1);

    if (isBreather) {
      checkpoints.push({ x: step.x + step.width / 2, y: step.y - 30, reached: false });
      sinceBreather = 0;
    }
  }

  // Final platform + finish checkpoint.
  const finalWidth = 380 + Math.floor(rand() * 60);
  let finalGapDx = 150 + Math.floor(rand() * 60);
  const finalRise = Math.round((rand() - 0.5) * 30);
  while (finalGapDx > 60 && !canSingle(finalGapDx, finalRise)) finalGapDx -= 10;
  const finalX = curX + finalGapDx;
  const finalY = curY - finalRise;
  platforms.push({ x: finalX, y: finalY, width: finalWidth, height: 20 });
  checkpoints.push({ x: finalX + finalWidth / 2, y: finalY - 30, reached: false });

  // --- Pass 2: decide which candidate steps become moving/ghost/melt/bounce/conveyor ---
  // Every position is finalized now, so — unlike deciding this per-step
  // during generation — each candidate can be checked against its actual
  // current solid neighbors (accounting for earlier conversions in this
  // same pass) before committing to making it intangible.
  function solidNeighbors(index) {
    let before = null;
    for (let i = index - 1; i >= 0; i--) {
      if (!platforms[i].ghost) { before = platforms[i]; break; }
    }
    let after = null;
    for (let i = index + 1; i < platforms.length; i++) {
      if (!platforms[i].ghost) { after = platforms[i]; break; }
    }
    return { before, after };
  }

  const ghostCut = ghostShare;
  const meltCut = ghostCut + meltShare;
  const bounceCut = meltCut + bounceShare;
  const conveyorCut = bounceCut + conveyorShare;

  candidateIndices.forEach((index) => {
    if (rand() >= movableChance) return;
    const step = platforms[index];
    const subRoll = rand();

    if (subRoll < ghostCut) {
      // Ghost platforms are excluded from the "is this level completable"
      // check (see .claude/audit-gaps.js) — removing this one must still
      // leave its solid neighbors a feasible double jump apart, or this
      // would silently become an unintended, unvalidated mandatory gate.
      const { before, after } = solidNeighbors(index);
      if (before && after) {
        const gap = after.x - (before.x + before.width);
        const rise = before.y - after.y;
        if (rise > 0 && !canDouble(gap, rise)) return; // leave it solid
      }
      step.ghost = true;
      step.ghostPeriod = Math.max(120, 200 - Math.round(80 * t));
      step.ghostOnRatio = Math.max(0.4, 0.65 - 0.25 * t);
    } else if (subRoll < meltCut) {
      // Melt platforms count as solid (they're always there the first
      // time you reach them — see docs/gameplay.md), so no feasibility
      // recheck is needed here.
      step.melt = true;
      step.meltDelay = Math.max(20, 30 - Math.round(10 * t));
    } else if (subRoll < bounceCut) {
      // Bounce pads (game.js's BOUNCE_STRENGTH) always sit on an already
      // solid, already-reachable step — they only ever add a faster/higher
      // optional route on top of it, never something a gap's base
      // feasibility depends on, so no recheck is needed here either.
      step.bounce = true;
      step.bounceStrength = -16 - Math.round(rand() * 4);
    } else if (subRoll < conveyorCut) {
      step.conveyor = true;
      const dir = rand() < 0.5 ? -1 : 1;
      step.conveyorSpeed = +(dir * (0.9 + rand() * 1.3)).toFixed(2);
    } else {
      step.moveAxis = rand() < 0.6 ? "x" : "y";
      step.moveRange = Math.round(moveRangeBase * (0.7 + rand() * 0.6));
      step.moveSpeed = +(moveSpeedBase * (0.8 + rand() * 0.5)).toFixed(3);
      step.movePhase = +(rand() * 6.28).toFixed(2);
    }
  });

  // --- Pass 3: crisscrossing red decoys ---
  // For some of the moving solid platforms just assigned above, spawn a
  // moving DEADLY twin nearby on the opposite axis, so its sweep visibly
  // crosses the safe platform's — the obvious "which one do I land on?"
  // trick the difficulty ramp leans on more from here on. Kept a safe
  // distance from every checkpoint placed so far (a hazard is never the
  // thing camping right next to a respawn point — see
  // .claude/audit-checkpoints.js) and excluded from every feasibility
  // check the same way the original static decoys always were (it's a
  // freestanding hazard next to the path, not part of it).
  candidateIndices.forEach((index) => {
    const step = platforms[index];
    if (!step.moveAxis || rand() >= crisscrossChance) return;
    const twinX = step.x + (rand() < 0.5 ? -1 : 1) * (40 + rand() * 50);
    const twinY = step.y + (rand() < 0.5 ? -1 : 1) * (25 + rand() * 35);
    const twinCenter = { x: twinX + step.width / 2, y: twinY };
    const tooCloseToCheckpoint = checkpoints.some(
      (c) => Math.hypot(c.x - twinCenter.x, c.y - twinCenter.y) < 110
    );
    if (tooCloseToCheckpoint) return;
    deadlyPlatforms.push({
      x: Math.round(twinX),
      y: Math.round(twinY),
      width: Math.max(50, Math.round(step.width * (0.55 + rand() * 0.35))),
      height: 14 + Math.floor(rand() * 12),
      moveAxis: step.moveAxis === "x" ? "y" : "x",
      moveRange: Math.round((step.moveRange || 60) * (0.75 + rand() * 0.5)),
      moveSpeed: +((step.moveSpeed || 0.03) * (0.85 + rand() * 0.4)).toFixed(3),
      movePhase: +(rand() * 6.28).toFixed(2),
    });
  });

  // --- Pass 4: spikes and static deadly decoys on whatever's left plain ---
  candidateIndices.forEach((index) => {
    const step = platforms[index];
    if (step.moveAxis || step.ghost || step.melt || step.bounce || step.conveyor) return;
    if (rand() < spikeChance) {
      // A lot more size variety than the hand-authored levels (which
      // mostly stuck to 20-30px), and — increasingly at higher difficulty
      // — a cluster of 2-4 spikes side by side instead of just one,
      // forming a real wall to clear rather than a single point hazard.
      const clusterChance = 0.15 + 0.4 * t;
      const clusterSize = rand() < clusterChance ? 2 + Math.floor(rand() * 3) : 1;
      const sizeMin = 12;
      const sizeMax = 26 + Math.round(28 * t);
      let sx = step.x + Math.max(8, Math.floor(step.width * (0.12 + rand() * 0.25)));
      for (let c = 0; c < clusterSize; c++) {
        const size = sizeMin + Math.floor(rand() * (sizeMax - sizeMin));
        if (sx + size > step.x + step.width - 6) break; // stay on the platform
        spikes.push({ x: sx, y: step.y, size });
        sx += size; // touching, side by side
      }
    }
    if (rand() < decoyChance) {
      deadlyPlatforms.push({
        x: step.x + step.width + 20 + Math.floor(rand() * 20),
        y: step.y + Math.round((rand() - 0.5) * 20),
        width: Math.max(60, Math.round(step.width * (0.5 + rand() * 0.4))),
        height: 20,
      });
    }
  });

  return {
    n,
    name: params.name,
    isBonus: params.isBonus,
    theme: params.theme,
    platforms,
    deadlyPlatforms,
    spikes,
    checkpoints,
  };
}

function serializePlatform(p) {
  // A missing field here silently serializes as the literal text
  // "undefined" — valid JS, but it poisons every downstream min/max in
  // applyLevelVerticalLayout() (game.js) with NaN, which then wrecks
  // every platform/checkpoint position in the whole level, not just this
  // one platform. Fail loudly here instead.
  for (const key of ["x", "y", "width", "height"]) {
    if (typeof p[key] !== "number" || Number.isNaN(p[key])) {
      throw new Error(`platform missing numeric ${key}: ${JSON.stringify(p)}`);
    }
  }
  const parts = [`x: ${p.x}`, `y: ${p.y}`, `width: ${p.width}`, `height: ${p.height}`];
  if (p.moveAxis) {
    parts.push(`moveAxis: "${p.moveAxis}"`);
    parts.push(`moveRange: ${p.moveRange}`);
    parts.push(`moveSpeed: ${p.moveSpeed}`);
    if (p.movePhase) parts.push(`movePhase: ${p.movePhase}`);
  }
  if (p.ghost) {
    parts.push(`ghost: true`);
    parts.push(`ghostPeriod: ${p.ghostPeriod}`);
    parts.push(`ghostOnRatio: ${p.ghostOnRatio}`);
  }
  if (p.melt) {
    parts.push(`melt: true`);
    parts.push(`meltDelay: ${p.meltDelay}`);
  }
  if (p.bounce) {
    parts.push(`bounce: true`);
    parts.push(`bounceStrength: ${p.bounceStrength}`);
  }
  if (p.conveyor) {
    parts.push(`conveyor: true`);
    parts.push(`conveyorSpeed: ${p.conveyorSpeed}`);
  }
  return `  { ${parts.join(", ")} },`;
}

function writeLevel(level) {
  const lines = [];
  lines.push(`// Level ${level.n} Data — "${level.name}"`);
  lines.push(`// Generated to fit the established difficulty tiers (see this`);
  lines.push(`// script's header and docs/gameplay.md) — every gap here is verified`);
  lines.push(`// against the same physics .claude/audit-gaps.js checks, and any`);
  lines.push(`// ghost-gated gap is confirmed to genuinely require the ghost platform.`);
  lines.push(``);
  // Bonus/branch levels show their real name in-game instead of the
  // generic "Level N" every ordinary generated level uses (see
  // docs/gameplay.md) — the whole point of naming them is that they read
  // as a distinct destination while you're actually playing them, not
  // just on the level map.
  const displayText = level.isBonus ? level.name : `Level ${level.n}`;
  lines.push(`window.levelText = ${JSON.stringify(displayText)};`);
  if (level.theme) {
    lines.push(`window.levelTheme = ${JSON.stringify(level.theme)};`);
  }
  lines.push(``);
  lines.push(`window.platforms = [`);
  level.platforms.forEach((p) => lines.push(serializePlatform(p)));
  lines.push(`];`);
  lines.push(``);
  lines.push(`window.deadlyPlatforms = [`);
  level.deadlyPlatforms.forEach((p) => lines.push(serializePlatform(p)));
  lines.push(`];`);
  lines.push(``);
  lines.push(`window.spikes = [`);
  level.spikes.forEach((s) => lines.push(`  { x: ${s.x}, y: ${s.y}, size: ${s.size} },`));
  lines.push(`];`);
  lines.push(``);
  lines.push(`window.checkpoints = [`);
  level.checkpoints.forEach((c, i) => {
    const tag = i === level.checkpoints.length - 1 ? " // Final" : "";
    lines.push(`  { x: ${Math.round(c.x)}, y: ${Math.round(c.y)}, reached: false },${tag}`);
  });
  lines.push(`];`);
  lines.push(``);

  return lines.join("\n");
}

const outDir = process.argv[2] || path.join(__dirname, "..");
const fromLevel = parseInt(process.argv[3] || "26", 10);
const toLevel = parseInt(process.argv[4] || "100", 10);

const results = [];
for (let n = fromLevel; n <= toLevel; n++) {
  const level = generateLevel(n);
  const content = writeLevel(level);
  results.push({ n, content });
}

results.forEach(({ n, content }) => {
  fs.writeFileSync(path.join(outDir, `level${n}.js`), content);
});
console.log(`Wrote ${results.length} level files (level${fromLevel}.js..level${toLevel}.js) to ${outDir}`);
